label chapter10:

    stop music fadeout 2.0
    scene bg yuri_bedroom
    with dissolve_scene_half
    play music t112

    "Abro mis ojos lentamente."
    "Agarro mi teléfono para mirar la hora."
    "Todavía es bastante temprano."
    "¿Ya salió el sol?"
    "Mirando a través de la ventana, parece que las nubes aún no se han desaparecido por completo."
    "Todavía hay un ligero chubasco."
    "Me levanto rápidamente y comienzo mi rutina normal."
    "Mientras me cepillo los dientes, recuerdo ese dia con del doctor Lankton."
    mc "El medicamento de Yuri..."
    mc "Y shus chushillos..."
    "Yuri ha estado rondando mucho por mi cabeza, ¿Que habrá sido de las demás chicas?"
    "Termino de cepillarme y bajo a la cocina."

    scene bg yuri_house_interior
    with wipeleft_scene

    mc "¿Bien que tenemos hoy?"
    "Abro el refrigerador y el aire frio choca en mi cara."
    mc "Absolutamente {w=0.5} nada."
    "Ahhhh y ahora que..."
    "Miro en la mesa y veo café instantaneo."
    "No sería suficiente."
    mc "Algo para comer, mmm..."
    "Necesito abastecer mi casa."
    "Me preparo una taza con el cafe de la mesa y me cambio para ir."
    #cambio de escena
    "Voy con el paraguas de Yuri a la tienda 24/7."
    "Mis pasos es lo unico que suena en el camino."
    "Aveces es tener bueno tiempo para uno solo, estar pendiente de alguien puede ser estresante."
    "Como Yuri."
    "Pero ese sentimiento que ella me da es suficiente."
    "Espero que nuestra relación dure mucho tiempo."
    "Cuando se solucione su afilado problema será mucho mejor."
    #cambio de escena
    "Llego a la tienda y tomo lo que necesito."
    "Leche."
    "Listo."
    "Jugo de naranja."
    "Listo."
    "Cereal."
    "Listo."
    "Pan."
    "Listo."
    "Camino por la sección de golosinas y veo un moño conocido."
    mc "Hola Sayori."
    s "¿[player] qué haces aquí?"
    mc "Solo comprando comida para comer."
    s "Duhh ¿Para que más?"
    "Recuerdo lo que dije hace unos instantes."
    "Enserio necesito comer algo."
    mc "¿Y tú qué haces aquí?"
    s "Emm yo pues ehhh..."
    s "Comprando cosas saludables."
    mc "¿Fruta?"
    s "Fruta eso, fruta."
    mc "¿En la sección de golosinas?"
    mc "¿En la mañana?"
    s "Solo me perdí."
    mc "Sé cuando mientes."
    s "Esta bien me atrapaste, ¿Contento?"
    mc "Suficiente para mí."
    "Veo que la conversación se puso un poco tensa asi que cambio de tema."
    mc "Ya que estamos aqui de todos modos, ¿Quieres comer algo por ahi?"
    s "Pero tú y Yuri están saliendo."
    mc "¿No que unos amigos no pueden salir sin intenciones de pareja?"
    s "No lo sé de todas formas Natsuki me estaba esperando."
    mc "¿Que estaban planeando?"
    s "Solo unas clases de cocina para mi."
    mc "¿Y si la cuenta va por mi parte?"
    s "..."
    s "Esta bien vamonos."
    "Terminamos de comprar algunas cosas y salimos a un restaurante cercano."
    "Marqué mi lista de provisiones y Sayori compró rollos de canela y una manzana."
    "Le dije que comprara esa manzana por decir que iba a comprar frutas."
    "Hizo un pequeño puchero pero al final cedió."
    "Entramos al restaurante y el ambiente cambio de uno frio a uno calido."
    mc "¿Que vas a pedir?"
    s "Una bobba de fresa y vainilla me parece bien, ¿y tú?"
    mc "Solo unos wafles con fresas."
    s "Eso suena delicioso, ¿Tambien puedo pedirlo?"
    mc "Vale pero solo por esta vez."
    "Llamamos a la camarera y toma nuestra orden."
    mc "Y bueno, ¿Cómo estas desde ese dia?"
    s "¿Cual día?"
    mc "Ese dia que supiste que yo y Yuri eramos algo."
    s "Ah..ese dia."
    s "Estoy mejorando."
    s "Natsuki tambien supo el problema que tenia y me ayudó con ciertas cosas."
    mc "Me alegra escuchar eso."
    mc "Tal vez al inicio no sabia como decirlo correctamente, pero sé que eres una persona fuerte."
    mc "Tengo unos planes con Yuri esta tarde pero te podré ver esta noche."
    s "¿Por que harias eso?"
    mc "Porque eres mi amiga de la infancia y me tengo que ayudarte."
    s "No merezco eso."
    "Ya se a donde va esta conversación."
    mc "Ya lo veremos en la noche, ¿Vale?"
    s "..."
    s "De acuerdo."
    "La camarera trae nuestros platos y comemos la mayor parte en silencio."
    "Pago la comida y nos vamos a nuestros respectivos hogares."
    scene bg yuri_house_interior
    with wipeleft_scene
    "Mando un mensaje a Yuri para vernos en la farmacia para recojer su receta."
    "Acepta y termino de guardar lo que compré."

    stop music fadeout 2.0
    scene bg waiting_room
    with wipeleft_scene
    play music t6

    show yuri 3ca zorder 2 at t11
    "Pasa un tiempo y veo a Yuri llegar a la farmacia."
    mc "¿Tienes la receta?"
    y "Sí, entremos"
    p "¿Le puedo ayudar en algo?"
    "Miro a Yuri."
    y 3cb "Prescripción para Yuri."
    p "¿Me puede dar su apellido?"
    y "Sí, es--"
    mc "Oh, mi zapato está desatado."
    show yuri zorder 1 at thide
    hide yuri
    "Miré hacia abajo y me di cuenta de que los cordones de mis zapatos izquierdos estaban desabrochados."
    "Me apoyo sobre una rodilla."
    "Das vuelta y vuelta y alar, y tus cordones atados estan."
    "Me levanto."
    show yuri 1ca zorder 2 at t11
    p "Aqui tienes."
    "El farmacéutico le entrega a Yuri una bolsa con una botella de pastillas."
    "Yuri revisa la etiqueta para aclarar que es la receta correcta."
    p "Deberá tomar su dosis dos veces al día, es decir, cada doce horas."
    y 1cs "Gra-gracias."
    p "De nada."
    "El farmacéutico nos da una gran sonrisa."
    mc "¿Eso es todo?"
    "Dirijmos miradas entre los dos."
    p "¿Tiene usted alguna duda?"
    y 3cj "No. Creo que lo entiendo todo."
    y 3cb "Gracias de nuevo."
    p "El gusto es mio."
    "Tomo la mano de Yuri y salimos del edificio."

    scene bg downtown
    with wipeleft_scene

    show yuri 3ca zorder 2 at t11
    mc "Muy bien Yuri, ¿Recuerdas que ibamos a tirar tu colección de cuchillos?"
    y 3cg "..."
    "Yuri se toma un momento para reflexionar sobre esto."
    "Es obvio que ella no comparte mi entusiasmo por eliminar su colección."
    "Quizás tenga una conexión más emocional de lo que pensaba."
    y 3cb "Eso suena como una buena idea, [player]."
    mc "Esa es mi especialidad."
    y 3cf "Tener buenas ideas."
    mc "No, ser llamado [player]."

    stop music fadeout 2.0
    scene bg yuri_house_interior
    with wipeleft_scene

    "Llegamos a la casa de Yuri."
    "Yuri está arriba. Dijo que quería cambiarse a algo más cómodo."
    "Me sentaré aquí y esperaré."
    play music t113
    "*bzzt*"
    mc "¿Eh?"
    "Busco en mi bolsillo para agarrar mi teléfono."
    "Me pregunto quién es."
    "Es un número desconocido."
    "¿¿¿???" "{i}Espero que estés disfrutando tus vacaciones.{/i} "
    "Espera."
    "Esta es la misma persona que me estaba enviando esos textos extraños hace unas semanas."
    "Escribo una respuesta."
    mc "¿Qué quieres?"
    "¿¿¿???" "{i}Tu sabes lo que quiero.{/i} "
    "¿¿¿???" "{i}Sin embargo, todavía no me lo has dado.{/i} "
    "Esto es ridículo."
    mc "No sé lo que quieres, así que déjame en paz o llamaré a la policía."
    "¿¿¿???" "{i}Si no quieres que le pase nada, termina con ella.{/i} "
    "¿¿¿???" "{i}El tiempo corre [player], no te tardes...{/i} "
    "¿Tiempo?"
    "¿Qué demonios significa eso?"
    stop music fadeout 1.0
    y "¿[player]?"
    mc "¡Ah!"
    show yuri 2bt zorder 2 at t11
    "Me giro para ver a Yuri detrás de mí."
    y "¿Está todo bien?"
    mc "Ahh, sí. Si, todo esta bien."
    "Deslizo mi teléfono de nuevo en mi bolsillo."
    mc "Me quedé dormido esperándote, así que me asustaste un poco."
    y 2bj "Mis disculpas."
    mc "Está bien."
    mc "¿Estas lista ahora?"
    y 3bw "*inhala*"
    y 3bb "Ok."
    "Subimos las escaleras."

    stop music fadeout 2.0
    scene bg yuri_bedroom
    with wipeleft_scene
    play music t107

    show yuri 3bu zorder 2 at t11
    "Entramos en su dormitorio."
    show yuri at s11
    "Nos sentamos en el suelo."
    "Yuri mete la mano debajo de la cama y saca una caja de madera del tamaño de un maletín."
    "Abre los pestillos y la parte superior se abre."
    mc "..."
    "Mis ojos brillan de asombro."
    "Hay una verdadera coleccion de todo tipo de cuchillos."
    "Desde navajas de bolsillo, hasta navajas mariposa."
    "Puntas de aguja, puntas Tanto, espalda recta."
    "Tampoco es solo el tipo de cuchillos."
    "Todos son exóticos con su propio diseño y color únicos."
    mc "Wow..."
    "Eso es todo lo que puedo decir en este momento."
    "Nunca pensé que usaría la palabra hermoso para describir un cuchillo."
    "¿Cómo podrías adquirir piezas como estas?"
    y 2bs "Son hermosos, ¿no?"
    "Sacó las palabras de mi boca."
    mc "Si..."
    "Pensé que tal vez solo tuviera unas cuantas navajas de bolsillo."
    "Sin embargo, esto es bastante increíble."
    y 1bb "Éste es mi favorito."
    "Ella saca uno."
    "Es de acero sólido con ondas de color azul claro grabadas en él."
    "La veo girarlo con sus delgados dedos."
    y 1bs "¿Te gustaría...sostener uno?"
    "Asiento con la cabeza."
    "Yuri cuidadosamente me entrega el cuchillo como un sensei entregándole una espada a su disipulo."
    "Sostengo el cuchillo en mi mano dominante."
    "Es mucho más pesado de lo que pensaba."
    "Cuando le doy la vuelta, su hoja azul claro refleja la luz."
    "Por curiosidad, paso mi pulgar sobre la hoja."
    mc "Esta afilado."
    y 2bf "Sin embargo, parece que lo manejas bastante bien."
    mc "Yo no diría eso. Más aún, tengo el sentido común de no pincharme el dedo con la punta de un cuchillo."
    y 2bs "..."
    "Yuri continúa viéndome examinando la hoja."
    y 2bv "Sabes, [player]..."
    y "Durante mucho tiempo estas fueron las únicas cosas que tuve."
    y "Creo que es hora de dejar esto en el pasado."
    y "Gracias por obligarme a hacer esto."
    y "Porque no lo hubiera hecho por mi cuenta."
    mc "No es nada Yuri, tú eres una persona muy buena y el primer paso para cambiar de pagina son esos cuchillos."
    mc "Además al verte a los ojos... "
    mc "Sé que todo saldrá bien."
    y 3bu "..."
    y 1bb "¿Que hubiera pasado si no nos hubieramos conocido?"
    mc "Pues..."
    mc "Yo estaría jugando videojuegos encerrado en mi habitación."
    mc "Y pues tú seguirias leyendo libros en un club que no se hubiera clausurado."
    mc "Creo que tú hubieras tenido un mejor futuro que él mio."
    y "¿Por qué lo dices [player]?"
    mc "Pues eres inteligente y muy bonita."
    mc "Sin contar lo de los poemas."
    "Yuri suelta una risa nerviosa."
    y "Aunque seguiria con mis problemas."
    mc "Si tienes razon, mejor hay que terminar con eso."
    mc "¿Nos vamos?"
    y "*Suspiro*"
    y "Si vamonos."
    "Nos levantamos y vamos a una casa de empeño."
    #https://www.youtube.com/watch?v=TmgbaV3dWMs
    "Vendedor" "¿Si que les puedo ofrecer?"
    mc "Um..."
    mc "Si buenas tardes quisieramos empeñar esta colección de cuchillos."
    "Vendedor" "Dejame echarle un vistazo"
    "El vendedor separa los cuchillos por marca y por tamaño haciendo varias filas y columnas."
    "El vendedor hace una llamada y nosotros nos miramos confudidos."
    "Un momento despues viene un señor analiza los cuchillos, hace las cuenta y mira a Yuri."
    y 2be "¿3000?"
    mc "¿Es una broma verdad?"
    y "Estos cuchillos deberian costar más que eso."
    mc "3000 yenes es una ridiculez por la cantidad de cuchillos que hay."
    "Vendedor" "No 3000 yenes, 3000 dolares."
    "Yo y Yuri nos quedamos boquiabiertos."
    y 3bj "Ese es un gran número."
    mc "3500 y es un trato."
    "Él acepta y le entregamos la colección."
    "Salimos del local y veo a Yuri sosteniendo un cuchillo en la mano."
    mc "Pensé que ibamos a deshacernos de todos."
    y "Pero este es mi favorito, no podria haberlo hecho."
    y "Por favor dame más tiempo [player] y te juro que lo botaré."
    "El sentimiento de emocion por ver varios billetes y la hipocresia me da un mal sabor de boca."
    mc "Por favor hazlo Yuri es lo mejor para ti."
    "Ella asintió suavemente y vamos a su casa."

    scene black
    with wipeleft_scene
    pause 1.0

    scene bg hospital
    with wipeleft_scene


    "Es hora."
    "Voy a la casa de Sayori."
    "Toco la puerta."
    "Nadie."
    "Intento de nuevo pero no recibo respuesta."
    "Llamo a Sayori por telefono."
    mc "¿Que tal con Natsuki?"
    "Intento y si contesta."
    n "¿Que quieres?"
    mc "Que me abras la puerta."
    n "Lo siento pero no estoy en casa, pidelo a Sayori."
    mc "No responde."
    n "Que extraño, ella a estado apagada ultimamente."
    "Es raro que en la mañana no la habia visto tanto de esa manera."
    mc "¿Entonces que hago?"
    n "No lo sé seguro tendrá una llave escondida o algo."
    mc "Claro gracias Natsuki."
    "Busco por los arbustos y nada."
    "Busco en alguna piedra."
    mc "Bingo."
    "Que raro que Sayori haya dejado su puerta cerrada ella siempre la deja abierta."
    "Aunque siempre le habia recomendado por su seguridad."
    "Entro a su sala y no hay nadie."
    mc "¿Sayori donde estas?"
    "El ambiente es vacio y hay un silencio sepulcral."
    "Miro en la cocina y no hay nadie."
    "El unico lugar que queda es el segundo piso."
    "Subo las escaleras."
    "El cuarto de Sayori está cerrado."
    "Toco la puerta suavemente."
    mc "¿Sayori recuerdas que ibamos a charlar sobre ello?"
    "..."
    "No escucho respuesta."
    "No me deja otra opción."
    "Tal vez está dormida o se está cambiando."
    "No pienses en ello, no escucho nada."
    mc "Sayori voy a entrar, ¿Está bien?"
    "..."
    mc "De acuerdo."
    "Abro la puerta gentilmente."
    mc "Sayori."
    s "..."
    mc "Sayori dime algo."
    s "mmm..."
    "Al parecer Sayori se habia quedado dormida."
    "Sacudo suavemente la cama."
    mc "Todavia es temprano para irse a dormir."
    "Sayori se voltea con marcas de que estaba llorando."
    mc "¿Estas bien?"
    s "¿Te parezco que estoy bien?"
    mc "Solo vine a charlar."
    s "No estoy bien para hablarte."
    mc "Porfavor Sayori dejame ayudarte."
    mc "Sé que he sido un tonto por no haberme dado cuenta que tenias depresión pero ahora puedo ayudar."
    mc "Solo dejame ayudar como un amigo."
    s "..."
    mc "..."
    "Sayori vuelve a llorar y le doy un abrazo."
    mc "Son esas nubes en tu vabeza que no te dejan ver la hermosa persona que eres."
    s "No quiero sentir este dolor."
    s "Me ha acompañado tanto tiempo y cada dia duele más."
    mc "Ya va a acabar y te vamos a ayudar."
    s "¿Quienes?"
    mc "Yo, Natsuki y Yuri."
    s "¿Y Monika?"
    mc "Y Monika."
    mc "Sonrrie más Sayori que asi te ves mejor."
    "Seguimos abrazados por un tiempo hasta que la respiración de Sayori se calma."
    s "Necesitaba esto."
    mc "Ves ahora te sientes mejor."
    s "Jeje gracias [player] eres el mejor."
    mc "Todo por mi mejor amiga Sayori."
    n "¡¡¡¡QUEEEEEE!!!!"
    n "¡SABIA QUE ERAS UN DEGENERADO!"
    n "¡¿CÓMO PUEDES TRAICIONAR A YURI ASÍ?!"
    s "No Natsuki no es lo que parece, [player] y yo estabamos teniendo una conversación."
    n "Si claro con besos y todo."
    n "Se lo voy a contar a Yuri."
    mc "Esto es un malentendido, te lo podemos explicar más tarde."
    "La expresión de Natsuki muestra varias emociones."
    "Pero en su mayoria ira."
    "Conversamos con ella un rato hasta que comprendio lo que estaba pasando."
    "Seguimos charlando de las cosas que pasaron en el tiempo en que no nos habiamos hablado mucho."
    "Y finalente me tuve que ir."
    mc "Cuidate Sayori y recuerda que siempre puedes contar conmigo."
    s "Gracias [player] por venir, te lo agradezco."
    n "Si la proxima vez que te vea no te vas a salvar [player]."
    mc "Entendido."
    "Entro a mi casa y doy un largo suspiro."
    mc "Ha sido un gran dia."
    mc "Espero que Yuri haga un buen uso del dinero que se ganó."
    "Me cepillo los dientes y me acuesto en la cama."
    "Mis parpado se sienten pesados."
    "Yuri y Sayori estaran bien..."



    scene black
    with dissolve_scene_full
    pause 1.0




    # TODO: aqui termina el guion de ruta neutra entregado. El hilo del acosador anonimo
    # (mensajes de chapter6/9/10) y el malentendido con Natsuki quedan sin resolucion.
    return