# Continuacion exclusiva de la ruta buena (dos semanas despues del dia 1)
# Contenido original de cap3.rpy a partir de "Unos dias despues", movido aqui al separar
# el guion base (compartido por todas las rutas) del guion exclusivo de la ruta buena.

label ruta_buena_semana2:

    call time_skip("Unos días después") from _call_time_skip_3

    "Hoy he despertado en mi propia cama."
    "No leímos la última noche juntos, así que ella está sola en su casa."
    "En realidad, nuestras conversaciones durante esta semana han sido... mínimas."
    "Algunos mensajes cortos."
    "Respuestas tardías."
    "Excusas para terminar rápido las conversaciones."
    "Desde que mencioné la idea de buscar ayuda profesional, Yuri se ha sentido más distante."
    "Yuri se ve a sí misma como una especie de loca, y quiero creer que un psiquiatra le ayudará a"
    "quitarse esa imagen."
    "De igual forma, esto es importante, le recordé a Yuri por mensaje que después de la escuela"
    "deberíamos ir."
    "Miro afuera en mi ventana."
    "Está un poco nublado, pero eso no va a pararme"
    "Continúo mi aburrida rutina de bañarme, cepillar mis dientes y vestirme."
    "Me dirijo a la cocina."
    mc "Qué como... ¿Qué como?"
    "Abro y cierro varios gabinetes una y otra vez, descartando comidas que no sean desayuno."
    mc "Oh"
    mc "¡Entonces será cereal!"
    "Lleno un tazón de cereal de maíz."
    "Abro suavemente el refrigerador."
    mc "No, no, no no, no..."
    "Ya no tengo leche."
    "Este es el peor día de mi vida."
    "Tal vez pueda encontrar un substituto."
    "Miro entre lo más profundo de la nevera."
    "Un envase de jugo de naranja."
    "Miro de nuevo al tazón."
    "Miro al jugo de naranja."
    "Miro de nuevo al tazón."
    mc "Esto es horrible, pero no hay de otra."
    "Señor, perdóname por esta aberración culinaria."
    # "Transportamos el escenario a un salón de clases"
    "La última clase casi termina."
    "Miro el reloj de la pared."
    "Nunca pensé que una hora pudiera sentirse tan larga."
    "Ni siquiera estoy escuchando al profesor."
    "Mi cabeza sigue regresando al mismo pensamiento."
    "¿Y si Yuri se arrepiente?"
    "¿Y si dejo las cosas peor?"
    "La campana suena."
    mc "Tomo un atajo entre el patio para ir a verme con Yuri."
    "Mi mente está quemándose ahora mismo."
    "Aún tengo dudas de lo que pueda pasar si llevo a Yuri con un profesional."
    mc "Tomo un atajo entre el patio para ir a verme con Yuri."
    "Mi mente está completamente ocupada."
    "???" "¡[player]!"
    "Me detengo al escuchar mi nombre."
    "Esa voz..."
    "Me giro lentamente."
    mc "...Monika."
    m "Hola."
    "La saludo por simple educación."
    mc "Hola."
    mc "¿Ya te ibas?"
    m "Sí..."
    m "En realidad..."
    "Juega distraídamente con la manga de su uniforme."
    m "¿Podemos hablar un momento?"
    "No esperaba escuchar eso."
    "Después de todo lo que pasó en el club, pensé que evitaría acercarse a mí."
    "Y, siendo sincero..."
    "Yo tampoco tenía muchas ganas de hablar con ella."
    mc "Lo siento."
    mc "Tengo algo importante que hacer."
    m "No tardaré mucho."
    "Hago un pequeño silencio."
    "En la distancia alcanzo a distinguir una figura de cabello morado cerca de la salida."
    "Yuri."
    "Seguramente está esperándome."
    mc "¿De qué querías hablar?"
    m "baja un poco la mirada."
    "Durante unos segundos parece buscar las palabras."
    m "He estado pensando bastante desde lo del club."
    m "Sé que probablemente ninguno de ustedes quiera verme."
    m "Y..."
    m "Supongo que lo entiendo."
    "Honestamente no esperaba escuchar eso."
    m "Solo quería decir que..."
    m "...nunca quise que termináramos de esta forma."
    "La miro unos segundos."
    "No parece estar intentando convencerme de nada."
    "Simplemente se ve cansada."
    mc "Nunca pensé que quisieras destruir el club."
    "Monika levanta ligeramente la vista."
    mc "Pero eso fue lo que terminó pasando."
    "El silencio que sigue se siente mucho más largo"
    "Monika baja lentamente la cabeza."
    m "...Supongo que sí."
    "Por un momento ninguno de los dos dice nada."
    m "respira profundamente."
    m "Aun así.."
    m "Sigo creyendo que había cosas que no estaban bien."
    m "Solo..."
    "Duda."
    m "...creo que no supe cómo decirlas."
    "Sus palabras suenan mucho menos seguras que antes."
    "Como si ni ella misma se lo creyera"
    "Miro nuevamente hacia la salida."
    "Yuri sigue esperándome."
    mc "Tengo que irme."
    m "asiente despacio."
    m "Sí."
    m "No quiero retrasarte."
    "Empiezo a caminar."
    "Despues de unos pasos..."
    m "¿(Jugador)?"
    "Me detengo."
    m "Espero que Yuri esté bien."
    "Sorprendentemente."
    "Suena sincera."
    mc "... Yo también."
    "Continuo caminando."
    "Después de unos segundos, ya no puedo escuchar sus pasos detrás de mí."
    # POV Monika
    "Me quedo inmóvil observando cómo (player) se aleja."
    ""
    "No salió como esperaba."
    "Ni siquiera sé qué esperaba."
    "Bajo lentamente la mirada."
    m "Destruí el club..."
    "Ese pensamiento sigue dando vueltas dentro de mi cabeza."
    "No..."
    "Yo solo quería ayudar."
    "... ¿Verdad?"
    "Comienzo a caminar sin una dirección clara."
    "El patio de la escuela está casi vacío a esta hora."
    "Todo se siente extrañamente silencioso."
    "???" "¿Monika?"
    "Levanto la vista."
    "Sayori."
    s "Pensé que ya te habías ido."
    m "Si..."
    m "Solo estaba..."
    "No terminó la frase."
    "Sayori me observa unos segundos."
    "Con preocupación."
    s "¿Hablaste con (player)?"
    "asiento levemente."
    s "¿Cómo salió?"
    "..."
    m "...No muy bien."
    s "guarda silencio."
    "Después se sienta en una banca cercana."
    s "¿Puedo decirte algo?"
    m "...Claro."
    s "sonríe con tristeza."
    s "Creo que tú sí querías ayudar."
    "Mis ojos se abren un poco."
    s "Nunca pensé que quisieras hacer daño."
    "Desvío la mirada."
    m "...Entonces, ¿por qué salió todo tan mal?"
    s "permanece pensativa unos segundos."
    s "Porque a veces las cosas no salen como esperas"
    s "Si, fuiste algo impulsiva antes."
    s "Pero siempre habrá oportunidad de mejorar"
    s "Es lo mejor que podemos hacer cuando tropezamos."
    "El viento mueve suavemente los árboles."
    "Ninguna de las dos habla durante unos segundos."
    m "...No sé si todavía pueda arreglar algo."
    "Sayori sonríe con la misma calidez de siempre."
    s "No lo sé."
    s "Pero creo que empezar a hacer las cosas diferente..."
    s "...es mejor que no intentarlo."
    "La observo."
    "No responde como esperaba."
    "Solo me recordó que todavía puedo decidir quién soy"
    "Quizá no pueda cambiar lo que hice."
    "Pero todavía puedo cambiar la forma en la que actuaré ahora."
    "Debo intentarlo."
    "Incluso si nadie me perdona."
    "Es lo mínimo que puedo hacer."
    # CAMBIO DE POV DE VUELTA AMC #Cambiamos de escena y nos encontramos a Yuri más
    "cerca de la salida."
    "Puedo notar cómo Yuri evita hacer contacto visual conmigo, parece incómoda por algo."
    "Me acerco, preocupado."
    mc "¿Yuri? ¿Está todo bien?"
    "Yuri se prepara antes de hablar, parece dudar antes de hablar."
    "Finalmente dice:"
    y "¿Has estado con Monika?"
    "Su voz suena en un tono mucho más bajo de lo normal."
    "Supongo que está nerviosa y preocupada."
    "¿Cómo no estarlo?"
    "Después de todo, aún no supera del todo lo ocurrido en el Club, pese a que ya pasó un tiempo."
    mc "Sí, hablamos un poco... Pero te prometo que no te tienes que preocupar por eso ahora."
    "Ella levanta la mirada."
    "Sus ojos reflejan inseguridad."
    y "N-no pelearon por mi culpa, ¿Verdad?"
    "Yuri lo pregunta como si cada palabra le pesara demasiado."
    "Evita mirarme directamente."
    mc "Yuri..."
    "Tardo unos segundos en responder."
    mc "No creo que seas la culpable de esto."
    mc "Las cosas entre Monika y yo ya estaban mal desde antes."
    y "¿De verdad...?"
    mc "Sí..."
    "Las palabras de Monika todavía siguen dando vueltas en mi cabeza."
    "Pero cuando veo a Yuri así de nerviosa, lo único que quiero es evitar que siga culpándose."
    mc "No hiciste nada malo por sentirte mal, Yuri."
    mc "tampoco tienes que cargar con todo esto sola."
    "Yuri baja lentamente la mirada."
    "Sus hombros dejan de verse tan tensos."
    "Como si por fin pudiera respirar un poco mejor."
    "Tras decir eso, Yuri empieza a respirar más lento."
    "Baja la mirada y deja de tensarse tanto, parece menos cargada."
    mc "(En un tono más suave)"
    mc "Oye..."
    mc "Todavía tenemos que ir a la cita."
    mc "¿Te parece si vamos?"
    mc "Juntos."
    "Ella me mira más calmada."
    y "Sí, vamos."
    mc "Tomo su mano suavemente contra la mía."
    mc "Yuri, mírame."
    mc "Intentaré que todo salga bien, lo prometo."
    mc "Allá vamos."
    # Se transporta el escenario a una sala de espera.
    mc "Vale, aquí es."
    "Miro al reloj colgando encima de la puerta."
    mc "Justo a tiempo."
    mc "El psiquiatra debería estar aquí en cualquier segund-"
    "Sin tiempo para terminar mi oración, un hombre sale de una habitación."
    "Es un hombre en la edad adulta, no es tan joven ni tan señor, con un cabello negro que empieza"
    "por un gris"
    "Él viste uno de esos trajes de moda, un traje típico de una revista de ropa"
    "Unos buenos zapatos elegantes, una corbata negra, incluso tiene un reloj de oro, parece real..."
    dr "Doctor Peter Lankton, psiquiatra."
    dr "Es un placer conocerlo."
    "Tenemos un apretón de manos."
    dr "Tú debes ser [player], ¿Correcto?"
    mc "Sí señor, y esta es Yuri."
    "Él aprieta la mano de Yuri"
    y "..."
    "Bueno, esto es incómodo..."
    dr "Ah, comprendo. Puede que estés nerviosa porque soy doctor. Lo sé."
    dr "Pero quiero que sepas que no hay nada que temer."
    "Él señala con su brazo la oficina."
    dr "Entonces, ¿Quieres pasar e iniciamos la sesión?"
    mc "Está bien, vamos."
    dr "Oh, lo lamento joven, pero por hoy quisiera solo hablar con la chica."
    mc "¿Qué? ¿En serio?"
    dr "Solo por ahora. En las próximas sesiones podrás pasar, pero para la primera es mejor"
    "que sea entre doctor y paciente."
    "Supongo que puedo entender eso..."
    "Okay, esperaré aquí."
    dr "Gracias por entenderlo."
    "Él se dirige a Yuri, quien no ha dicho ni una sola palabra desde que llegamos."
    dr "¿Deberíamos pasar?"
    y "..."
    dr "..."
    mc "¿Doctor, le importaría si hablara con ella por un momento?"
    dr "No. Tómense su tiempo. Estaré en mi oficina, que entre cuando este lista."
    "Él entra a su oficina y cierra la puerta."
    mc "¿Qué estás pensando ahora mismo?"
    y "N-no...no p-puedo hacerlo."
    mc "No digas eso."
    "Pongo mis manos en sus hombros."
    mc "Escúchame."
    mc "Eres fuerte, puedes pasar por esto."
    mc "Cuando entres estaré aquí, y cuando salgas también estaré aquí."
    mc "Se que puede dar miedo abrirse a un completo extraño."
    mc "Pero necesito que nos ayudes a ayudarte. "
    y"..."
    "Yuri me mira fijamente."
    y "Okay..."
    y "Lo haré lo mejor que pueda."
    mc "Eso es todo lo que pido."
    "Le doy un abrazo, y ella entra a la oficina."
    # Cambio de escena dentro de la consulta, perspectiva de Yuri
    "Aún dudando, entro a la consulta despacio."
    "Miro al suelo."
    "aprieto ligeramente las manos."
    "Doy un pequeño paso dentro y luego otro."
    # Nota: En esta parte pensé que podrían los artistas hacer un sprite del Dr. Lankton, pero es solo una
    "idea, todo puede cambiar si no están de acuerdo conmigo, estas son solo ideas que forman parte de"
    "un guion descartable y estoy totalmente bien si no están de acuerdo conmigo."
    "El Dr. Lankton ya está sentado."
    "Él levanta la mirada para observarme con calma."
    "El Dr. Lankton se levanta ligeramente, solo lo justo."
    dr "Puedes sentarte donde te sientas más cómoda."
    "Asiento sin hablar."
    "Me siento en la silla frente al doctor."
    mc "acomodo la ropa."
    "Me cuesta mantener contacto visual."
    "Él se vuelve a sentar."
    "Se acomoda en la silla."
    "Hay un silencio breve."
    dr "Antes de empezar... esto es un espacio privado."
    dr "No tienes que decir nada que no quieras."
    dr "Podemos ir a tu ritmo."
    "Él baja el tono al decir esto último"
    "Asiento muy levemente."
    "Bajo la mirada y mis dedos se aprietan un poco más."
    "Hay un silencio nuevamente."
    dr "Dime joven, ¿Qué te hizo venir hoy?"
    # Hay dos botones con dos opciones, la primera es "No lo sé... últimamente me siento rara y la
    #"otra es "Me cuesta mucho hablar con la gente", aunque en cualquiera de las dos el doctor dirá lo"
    "mismo, son meramente un detalle."
    dr "Entiendo."
    "Hay una pausa."
    "El doctor junta las manos."
    dr "¿Esto te pasa desde hace mucho tiempo?"
    "Miro hacia un lado"
    "Empiezo a dudar de si debería estar aquí."
    "Respiro suavemente, tratando de calmarme."
    "Inconscientemente, me acomodo la manga"
    mc "Quedo paralizada cuando siento que el doctor ha mirado unas marcas breves"
    "Un terror indescriptible inunda mi mente."
    "Él rápidamente me mira a los ojos nuevamente sin decir nada"
    dr "A veces, este tipo de pensamientos vienen de algo más grande"
    dr "Y no siempre es fácil hablarlo de inmediato"
    # Vuelven a haber dos opciones, la primera es " No...solo es eso y la segunda es "Hay cosas que
    "no sé cómo explicar bien."
    # Si escogemos la primera opción, el Dr. Lankton dirá lo siguiente:
    dr "Está bien. Podemos empezar por ahí entonces."
    "Si escogemos la segunda opción, el Dr. Lankton dirá"
    dr "Gracias por decírmelo."
    dr "No tienes que cargar con esto sola aquí."
    "El doctor se reclina ligeramente."
    # En cualquier opción, la sesión terminara así:
    dr "Podemos tener más sesiones para hablar de esto si así lo deseas."
    "Si quieres puede acompañarnos tu amigo a las siguientes sesiones."
    "Miro mis manos."
    "La sesión ha finalizado..."
    # Cambio de escena, volvemos a la perspectiva del Jugador.
    mc "Bueno, supongo que me quedare aquí esperando."
    "Tomo asiento, y miro alrededor."
    "La sala de espera está llena de posters motivacionales, imágenes y otras cosas estúpidas."
    "-Miro hacia otra pared"
    "Un certificado de psicólogo Dr. Peter Lankton, blah, blah, blah, Universidad de Stanford, blah,"
    "blah, blah..."
    "Se ve que este tipo sabe totalmente de esto."
    "Eso me deja más tranquilo."
    " Por primera vez en este mes puedo relajarme un poco."
    "Quizás Yuri pueda tener la ayuda que necesita"
    "Después de unos minutos el Dr. Lankton y Yuri salen de la oficina."
    "Empujando a un lado mis pensamientos, me paro de la silla para hablar con él."
    mc "¿Todo bien Doctor?"
    dr "Tu amiga parece estar lidiando con algunos problemas."
    "Lo miro de forma confusa."
    mc "Ya veo..."
    dr "Aún es pronto para saber todo lo que está sintiendo."
    dr "Considero que deberíamos trabajar en eso para ayudarla mejor."
    dr "Creo que sería bueno hacer otra citación, para poder ayudarle un poco mejor al"
    "respecto."
    dr "Recuerden que hay terapias, y médicos profesionales como yo que están al servicio"
    "para ustedes."
    "Él me da una sonrisa."
    mc "Gracias Doctor."
    mc "Y qué hay de lo que ella de... usted sabe..."
    dr "Lo siento, pero si te refieres a algo de la consulta, eso es información privada la cual"
    "no puedo revelar."
    "Confidencialidad entre Paciente y Doctor."
    "Hay un extraño cambio en mi voz cuando dirijo ese término a él."
    dr "Por supuesto, si ella quiere revelarte esa información, es la elección de ella."
    mc "Gracias Doctor."
    dr "Un placer."
    "Le doy un último apretón de manos y salgo con Yuri del edificio."
    "El resto de caminar a casa es tranquilo."
    "Ninguno de nosotros elije decir una palabra."
    "Vuelvo a sentir esa sensación de culpa, quizás fue muy duro para ella que yo la haya llevado a un"
    "sitio así."
    "Incluso pese a que era con buena intención."
    # Llegan a la casa
    "Caminamos adentro de la casa y Yuri toma asiento en el sofá."
    "Me paro enfrente de ella. Antes de sentarme y hablar con ella."
    "Necesito disculparme."
    mc "Yuri, yo-"
    y "[player]..."
    "Ella cubre su cara con sus manos."
    y "F-fue extraño."
    y "No sabía muy bien que decir."
    y "Fue más difícil de lo que esperaba..."
    y "Creo que aún necesito tiempo para acostumbrarme..."
    "Pongo mi brazo alrededor de ella."
    mc "Yuri, yo debí saber que está mal forzarte a hacer algo como eso."
    "Ella baja su cabeza y se acerca más a mí."
    "Sus ojos lavanda están llenos de lágrimas."
    y "[player]... tú no me obligaste."
    y "Tú tienes razón para ayudarme..."
    y "Y-yo... quiero volver."
    y "¿Puedes programar otra cita?"
    "Estoy desconcertado."
    mc "¿En serio?"
    y "Yo sé que esto es lo mejor para mí... y tú estás de mi lado..."
    y "Yo creo que podemos superarlo."
    mc "Siempre estaré de tu lado Yuri."
    mc "Yo..."
    mc "Tenía miedo."
    mc "Miedo de hacerte pasar por mucho."
    mc "Y... miedo de que no estuvieras bien con esto y que solo quisieras hacerme sentir tranquilo."
    y "¿Puedes hacerme un favor, [player]?"
    mc "Por supuesto."
    y "No sé cómo podría explicarle todo al doctor."
    mc "-Bueno..."
    mc "Soy todo oídos si me necesitas."
    y "No sé cómo explicarlo..."
    "Yuri evita mirarme."
    y "A veces siento que mi cabeza... nunca se calla."
    mc "No tienes que decirme todo ahora."
    y "Pero quiero intentarlo."
    "Ella aprieta lentamente sus mangas."
    y "Cuando mis padres discutían"
    y "Cuando era más pequeña... los libros me ayudaban mucho a distraerme."
    y "Podía ignorar todo por un rato."
    "Yuri guarda silencio."
    y "Eventualmente mi madre se separó de mi padre y de mí, y mi padre tuvo que tener un trabajo"
    "extra para soporte."
    y "Con todo eso pasando yo solo continúe reprimiendo mis sentimientos y leyendo mis libros."
    "Así he estado toda mi vida."
    "Ella se detiene otra vez para respirar lentamente y reunir más sus pensamientos."
    y "Pero después dejaron de ser suficientes."
    "Yuri mantiene la mirada fija en el suelo"
    y "No sabía cómo sacar todo eso de mi cabeza."
    y "Ni siquiera sabía exactamente qué estaba sintiendo."
    "Ella aprieta sus mangas con más fuerza."
    y "Y un día... simplemente lo hice, comencé a usarlos."
    "Su voz se vuelve más baja."
    y "Me asusté mucho después."
    y "Pensé que nunca volvería a hacerlo."
    "Yuri guarda silencio unos segundos."
    y "Pero por un momento... mi cabeza se sintió más tranquila."
    y "Y terminé regresando a eso cada vez que me sentía sobrepasada."
    "Esto es mucho para digerir pero... solo quería decir..."
    mc "No te juzgo."
    y "¿Q-qué?"
    mc "No creo que merecieras pasar por todo eso."
    mc "tampoco creo que seas una mala persona por no haber sabido manejarlo."
    mc "A veces las personas simplemente... no saben cómo manejar lo que sienten."
    mc "Nunca podré entender lo que sucede en tu cabeza."
    mc "Pero estoy bien con eso."
    mc "Porque aún seguiré mi promesa de nunca dejarte."
    mc "Juntos podremos enfrentarlo."
    "Miro lentamente las vendas que cubren sus brazos."
    "Dudo unos segundos antes de hablar."
    mc "Yuri..."
    mc "¿Crees que podríamos guardar los cuchillos por un tiempo?"
    "Ella se tensa inmediatamente."
    y "..."
    mc "Solo quiero que estés un poco más segura."
    "Yuri baja la mirada."
    y "Está bien, te dejaré guardarlos (player)"
    "sonrió con orgullo"
    mc "Lo superarás Yuri"

    call time_skip("Unos días después") from _call_time_skip_4

    "Yuri sigue yendo a terapia"
    "Todavía hay momentos incómodos"
    "Pero empieza a mejorar poquito a poquito"
    "En realidad"
    mc "Hace tiempo que Yuri no sale a ningún lugar solo para relajarse"
    "Quizás mi idea suena algo cliché."
    "Pero honestamente... creo que a Yuri le gustaría." "Pronto comienzo a escribirle a Yuri"
    mc "Buenos días Yuri, ¿dormiste bien?"
    y "Sí, en realidad siempre despierto temprano. ¿Y tú?"
    mc "Oh bueno yo igual"
    "Gran mentira yo siempre duermo hasta tarde"
    mc "¿Oye, te gustaría ir a la playa al rato? Creo que nos vendría bien relajarnos"
    y "¿A la playa?..."
    "tarda unos segundos en responder probablemente pensándolo"
    y "Por supuesto (player), ¿a qué hora?"
    "Su respuesta llegó más rápido esta vez."
    "Por alguna razón... eso me hizo sonreír."
    mc "Muy bien, hora de ponerme guapo"
    "o al menos intentarlo"
    # cambio de escena a la puerta de la casa
    "Veamos...creo que tengo todo listo"
    "Tal vez debería llevarle algo a Yuri, espero encontrar algo en el camino"
    "Y barato, muy importante esa parte"
    # cambio de escena a casa de Yuri
    "Encontré unos chocolates, fallé en la parte de ser algo barato pero seguro que le gustarán"
    "*ding dong*"
    "Que no me reciba su padre, que no me reciba su padre"
    "No es un buen momento para conocerlo"
    "La puerta se abre y sale Yuri con un vestido blanco con flores moradas"
    mc "Oh..."
    "Por un segundo me quedo mirándola demasiado tiempo."
    mc "Ese es el vestido que compraste antes... ¿verdad?"
    "Yuri aparta ligeramente la mirada."
    y "S-si..."
    y "Es ese."
    y "Tú... te ves bien hoy también"
    "Bueno me atrapó, ahora yo soy el rojo"
    mc "Gracias Yuri, salgamos un rato"
    "Comenzamos a caminar juntos por la calle."
    "Al principio ninguno dice demasiado."
    "Pero curiosamente... el silencio no se siente incómodo, al menos yo me siento en paz y Yuri...."
    "Parece estar feliz también"
    y "Hace buen clima hoy..."
    mc "Sí."
    mc "Aunque pensé que haría más calor."
    "Yuri deja escapar una pequeña risa."
    "Es una risa suave."
    "Pero aun así logra hacerme sonreír."
    # cambio de escena a la playa
    "Llegamos hace unos minutos y la vista es hermosa"
    "Espera ese es... No puede ser"
    "¡Un señor que vende helados!"
    mc "Hey, Yuri, ¿quieres un helado?"
    "Yuri permanece mirando el mar."
    "Parece completamente distraída observando las olas."
    y "No traje dinero (player), ve y te espero aquí"
    "Bueno mi momento ha llegado"
    mc "Está bien Yuri, solo dime de qué lo quieres"
    "Yuri desvía la mirada y juguetea con su vestido, susurra algo que se escucha como 'fresa"
    "Sonrío por la linda reacción y compro los helados, luego vuelvo con Yuri"
    y "Gracias (player)"
    "Comenzamos a caminar cerca del mar"
    "El sonido de las olas llena el silencio entre nosotros."
    "Yuri sostiene sus sandalias entre las manos mientras caminamos cerca de la orilla."
    y "No recuerdo la última vez que vine a un lugar así."
    mc "¿Demasiada gente?"
    y "Mm... también."
    y "Pero supongo que nunca encontraba una razón para hacerlo."
    "El viento mueve ligeramente su cabello."
    mc "¿Y ahora?"
    "Yuri me mira por un momento antes de apartar la vista."
    y "Ahora creo que quería intentarlo."
    mc "Yo tampoco solía venir tanto, supongo que evitaba salir de mi cueva así que felicidades por lograr sacarme Yuri"
    "Yuri deja escapar una risita"
    y "Yo también lo evitaba, ¿recuerdas?"
    mc "Sí, somos igualitos"
    "Caminamos varios minutos más hasta encontrar una banca y por supuesto que nos sentamos"
    "En esta parte de la playa parece estar más vacía y el sol comienza a irse dándonos una linda vista"
    y "Eh (player)... Gracias por traerme aquí, necesitaba relajarme"
    mc "No tienes que agradecer Yuri, yo..."
    mc "Disfruto pasar tiempo contigo"
    "Ella desvía la vista al suelo con una sonrisa."
    "Por un momento ninguno dice nada."
    "El sonido de las olas llena el silencio entre nosotros."
    "Normalmente odiaría un silencio tan largo."
    "Pero con Yuri... no es incómodo."
    y "Me alegra haber venido."
    mc "A mí también."
    "Yuri juega distraídamente con la manga de su vestido."
    y "Siento que últimamente... todo ha sido menos pesado."
    "Ella sonríe levemente mientras mira el mar."
    y "Bueno no perfecto."
    y "Pero... mejor."
    "Escucharla decir eso me hace sentir extrañamente aliviado."
    mc "Has estado esforzándote mucho."
    y "Mm..."
    "Yuri guarda silencio unos segundos."
    y "Gracias por quedarte conmigo, [player]."
    "Mi pecho se siente extraño al escuchar eso."
    mc "No tienes que agradecerme tanto..."
    mc "Quiero estar aquí."
    "Las palabras salen antes de que pueda pensarlas demasiado."
    "Yuri lentamente me mira."
    "Por un segundo siento que mi corazón deja de funcionar."
    mc "Yo..."
    mc "Creo que nunca había querido pasar tanto tiempo con alguien."
    "Yuri baja lentamente la mirada."
    "Sus dedos aprietan ligeramente la tela de su vestido."
    y "Yo tampoco..."
    "El viento mueve suavemente su cabello."
    "Yuri duda unos segundos."
    "Después... lentamente acerca su mano a la mía."
    "Mi corazón empieza a latir muchísimo más rápido."
    mc "Últimamente..."
    mc "Siento que pienso demasiado en ti."
    "En cuanto las palabras salen de mi boca quiero esconderme debajo de la arena."
    "Yuri me mira sorprendida."
    mc "No, espera, eso sonó raro..."
    "Ella deja escapar una pequeña risa."
    "Y eso solo hace que me ponga todavía más nervioso."
    mc "Lo que intento decir es que..."
    mc "Me gusta pasar tiempo contigo."
    mc "Mucho."
    "Mi pecho late tan fuerte que estoy seguro de que Yuri puede escucharlo."
    "Ella aparta la mirada lentamente."
    y "[player]..."
    y "Creo que yo también me siento así."
    "Saber lo que acaba de decir Yuri me pone feliz y en lugar de ponerme más nervioso me tranquiliza"
    "Decido acercarme un poco más y Yuri hace lo mismo"
    "Al estar tan cerca... mi corazón late con fuerza pero poco a poco terminamos dándonos un lindo beso"
    "Por primera vez en mucho tiempo... mi mente se siente tranquila." "Yuri no parece estar tan diferente a mí, está... feliz"
    "Y mientras el sol termina de ocultarse..."
    "Por primera vez en mucho tiempo... el futuro no me parece tan aterrador."
    # Cambio de escena a la habitación de me
    mc "Vaya... sí que debí dormir temprano"
    "Después de una molesta alarma me levanto y me preparo para empezar el día"
    mc "Muy bien, ¿qué tenemos para desayunar hoy?"
    "¿No parezco un loco hablando solo, verdad?"
    "Después de desayunar algunos huevos me pongo a pensar qué haré hoy"
    mc "Todavía es temprano..."
    "Supongo que podría salir a correr un rato."
    "Hace siglos que no hago ejercicio."
    "De hecho estoy seguro de que Yuri puede levantarme como si fuera una rama"
    "Después de varios minutos corriendo no dejo de pensar en Yuri y todo lo de ayer, me pone tan feliz... pero a la vez estoy confundido"
    "De verdad somos nov-"
    "SMACK"
    "Me caí"
    mc "Maldita piedra..."
    "Espero que nadie haya visto eso"
    "Levanto la vista y hay una anciana paseando a su perro"
    mc "Eh se me cayó una moneda"
    "Su perro parece juzgarme"
    "Esto es humillante"
    # Cambio de escena al sofá de me
    mc "Bueno no pensé que regresaría con una bolsa de verduras congeladas"
    "*ding dong*"
    "¿Esa es Yuri? Aún estoy nervioso de verla después de ayer no nos hicimos novios oficialmente"
    "Me levanto la puerta y es... ¿Sayori?"
    s "Holaa (player) cuánto tiempo"
    s "Espera, ¿desde cuándo te gustan las verduras?"
    mc "Buenos días a ti también Sayo, y resulta que son buenas para el dolor de cabeza"
    s "¿Dolor de cabeza?"
    mc "No preguntes."
    s "Te caíste, ¿verdad?"
    mc "¿Qué?"
    s "Te caíste."
    mc "¿Cómo sabes eso?"
    s "Porque tienes una bolsa de verduras congeladas pegada en la cabeza."
    mc "..."
    s "Y porque eres tú."
    "Suspiro."
    mc "Sí, me caí."
    s "Jejeje."
    mc "No te rías."
    s "Lo intentaré."
    "Lo dice mientras sigue riéndose."
    s "Aunque debo admitir que me sorprende."
    mc "¿Qué cosa?"
    s "Que te vea sonriendo otra vez."
    "Parpadeo confundido."
    mc "¿Sonriendo?"
    s "Sí."
    s "Últimamente parecías muy preocupado."
    "Su sonrisa se vuelve un poco más suave."
    s "Me alegra verte mejor."
    "Por un momento no sé qué responder."
    mc "Gracias, Sayori."
    "Ella vuelve a sonreír con normalidad."
    s "¡Perfecto!"
    s "Ahora que ya confirmé que sigues vivo tengo otra pregunta."
    mc "Tengo miedo de preguntar."
    s "¿Qué pasó con Yuri?"
    mc "¿Qué?"
    s "Vamos, vamos."
    s "No nací ayer."
    s "Y además ustedes dos son pésimos ocultando cosas."
    mc "No estamos ocultando nada."
    s "Ajá."
    s "Claro."
    s "Y yo soy la presidenta de la Tierra."
    mc "Hola señora presidenta"
    "Sayo me golpea en el hombro, supongo que lo merecía"
    "Ambos pasamos a mi sofá"
    mc "Esta bien, Yuri había pasado por algunos problemas después de lo del club"
    mc "La estuve apoyando y esta mejorando poco a poco"
    s "Me alegra que esté mejorando, pero ¿qué hay entre ustedes ehh?"
    "Oh no ahora me molestará con esto hasta que sepa que salimos"
    mc "Bueno es mi amiga y la quiero igual que a ustedes."
    "Ni de broma igual que ellas."
    "Sayori me mira fijamente."
    "Demasiado fijamente."
    mc "¿Qué?"
    s "Nada."
    mc "Sayori."
    s "Nadaaa."
    "Definitivamente es algo."
    s "Solo estaba pensando que eres muy mal mentiroso."
    mc "¿Qué?"
    s "Cuando mientes miras hacia otro lado."
    mc "Eso no es cierto."
    s "Lo acabas de hacer."
    "Maldita sea."
    s "Así que..."
    "Se acerca un poco más."
    s "¿Te gusta Yuri?"
    mc "¿Qué clase de pregunta es esa?"
    s "Una muy simple."
    mc "Sayori."
    s "¿Si?"
    mc "Estás sonriendo demasiado."
    s "Porque sé que tengo razón."
    "Me dejo caer contra el respaldo del sofá."
    mc "Eres imposible."
    s "Entonces sí."
    mc "No dije eso."
    s "Tampoco dijiste que no."
    "Sayori levanta los brazos victoriosa."
    s "¡Ajá!"
    mc "No hagas eso."
    s "¡AJÁ!"
    "Creo que empiezo a entender por qué sus padres salen tanto."
    "Sayori se ríe durante unos segundos."
    "Pero poco a poco su sonrisa se vuelve más suave."
    s "Me alegra."
    mc "¿Eh?"
    s "Después de todo lo que pasó."
    s "Me alegra que los dos tengan algo bueno."
    "Por primera vez desde que llegó, su tono suena completamente sincero."
    s "Solo cuídala, ¿sí?"
    s "Y cuídate tú también, te ves cansado."
    "Creo que tiene un poco de razón, estos días lo han sido"
    mc "Estaré bien Sayo, ¿qué hay de ti?"
    "Sayori parece sospechar que no hable de mí, ¿desde cuándo es tan observadora?"
    s "Bueno, yo estuve ocupada con cosas de la escuela ya que no iba tan bien pero estoy mejorando mucho"
    s "Natsuki después de lo del club ha estado tomando clases de cocina y te sorprendería lo bien que lo hace"
    "Bueno eso suena muy Nat"
    s "Y Monika, no supe mucho de ella después de lo del club. Está esforzándose por una beca en la universidad y vaya que lo está logrando"
    "Monika nunca presumió sus calificaciones pero diablos ya eran muy altas en ese entonces"
    mc "Me alegra escuchar eso."
    s "¿Verdad?"
    s "Aunque extraño un poco el club."
    "Su sonrisa se vuelve un poco más pequeña."
    "Yo también."
    "Por más problemas que hubiera tenido, seguía siendo un lugar al que podía ir después de clases."
    mc "Sí"
    "Durante unos segundos ninguno dice nada."
    s "Oye."
    mc "¿Hm?"
    s "¿Crees que algún día podamos volver a reunirnos?"
    mc "¿El club?"
    s "Aunque no sea oficialmente."
    "Me quedo pensándolo."
    "Supongo que no sería imposible."
    "Yuri ya está mejorando."
    "Natsuki parece estar ocupada pero sigue cerca."
    "Y Sayori claramente echa de menos esos días."
    mc "Tal vez."
    s "¡Eso significa que sí!"
    mc "Eso no fue lo que dije."
    s "¡Lo fue para mí!"
    "Sayori vuelve a reírse."
    "Es extraño."
    "Por primera vez en semanas la conversación no gira alrededor de problemas."
    "Solo estamos hablando."
    "Como antes."
    s "Bueno."
    "Ella se pone de pie."
    s "Creo que ya molesté suficiente por hoy."
    mc "Eso significa que alguna vez dejas de molestar."
    s "¡Oye!"
    "Me golpea suavemente el brazo."
    "Otra vez."
    s "Ah, cierto."
    "Se detiene justo antes de llegar a la puerta."
    s "Si ves a Yuri..."
    mc "¿Si?"
    s "Dile que la extraño."
    "Su tono vuelve a sonar sincero."
    s "Y que me alegra que esté mejor."
    "Antes de que pueda responder, Sayori ya está saliendo por la puerta."
    "Qué mujer tan peligrosa."
    "Mi teléfono vibra."
    "Un nuevo mensaje."
    y "Buenos días, [player]."
    y "¿Cómo estás?"
    mc "Hola Yuri, me duele un poco la cabeza, ¿y tú?"
    y "¿Estás bien? Yo estoy bien, me siento liberada ahora estoy cocinando"
    mc "Estoy bien, yo... también me siento feliz, ¿quieres salir al rato?"
    "Yuri parece contestar más rápido esta vez"
    y "Sí, ¿a qué hora planeas venir?"
    "Nos ponemos de acuerdo"
    "Muy bien, tal vez sea nuestra oportunidad de aclarar las cosas entre nosotros"
    "Estoy nervioso"
    "Guardo el teléfono en mi bolsillo."
    "Supongo que ya no hay vuelta atrás."
    "Intento distraerme ordenando un poco la casa antes de salir."
    "Lo cual dura un rato hasta que termino."
    mc "Esto es inútil."
    "Entre más intento pensar en otra cosa, más termino pensando en Yuri."
    "¿Se supone que estar enamorado funciona así?"
    "Decido salir antes de volverme loco."
    # Cambio de escena a la calle
    "El aire de la tarde es agradable."
    "Camino tranquilamente mientras reviso la hora en mi teléfono."
    "Aún es un poco temprano."
    "Probablemente porque llevo media hora preparándome para una salida que ni siquiera es una cita oficial."
    n "¡Oye!"
    "Me detengo."
    "Conozco esa voz."
    "Y también conozco ese tonito."
    n "¡Tú!"
    mc "Hola, Natsuki."
    n "¿Hola, Natsuki?"
    n "¿Eso es todo?"
    n "Hace semanas que no te veo."
    mc "Tú tampoco me has buscado."
    n "Porque tengo cosas importantes que hacer."
    mc "¿Como qué?"
    n "Postres."
    mc "Entendible."
    "Por alguna razón parece satisfecha con esa respuesta."
    n "Entonces..."
    "Me señala con el dedo."
    n "¿Vas a ver a Yuri?"
    mc "¿Qué?"
    n "Era muy obvio."
    mc "¿Desde cuándo todo el mundo lo sabe?"
    n "No respondas una pregunta con otra pregunta."
    "Suspiro."
    mc "Sí."
    n "Ajá."
    "Su sonrisa se vuelve sospechosamente grande."
    mc "No hagas esa cara."
    n "¿Qué cara?"
    mc "Esa cara."
    n "La cara de que tengo razón."
    mc "Exactamente esa."
    mc "No tiene sentido ocultarlo, Sayori ya me atormentó con eso hace rato."
    n "¿Qué?"
    mc "Larga historia"
    n "¿Entonces cuándo lo van a hacer oficial?"
    mc "Bueno honestamente no tengo idea, ayer fue un día especial para ambos pero no le dije"
    "Natsuki suspira con una sonrisa"
    n "Esa Yuri, no debería decírtelo porque se supone que es tu novia pero estoy seguro de que estará lista"
    n "Más te vale que la cuides o haré ese moretón de tu cabeza más grande"
    "¿Espera, en serio se nota?"
    mc "No me atrevería a desafiarte"
    n "Como sea tengo que irme pero dale esto, dile que es de tu parte"
    "Natsuki me entrega una galleta en forma de gato"
    n "No creas que es porque quiero ayudarte tonto, quiero que ella sea feliz"
    "Clásica tsundere"
    mc "Gracias Nat, te debo una"
    n "Como sea tonto"
    "Natsuki desvía la mirada."
    "Juraría que estaba sonriendo."
    "Pronto se despide"
    "Guardo cuidadosamente la galleta."
    "Ahora tengo una misión."
    "No aplastarla antes de llegar."
    # Cambio de escena a casa de yuri
    "Tras caminar varios minutos finalmente llego a la casa de Yuri."
    "Respiro profundo."
    "Por alguna razón estoy más nervioso ahora que en la playa."
    "*Ding dong.*"
    "Escucho pasos acercándose."
    "La puerta se abre."
    "Yuri aparece frente a mí."
    "Y por un segundo olvido completamente lo que iba a decir."
    y "¿[player]?"
    mc "Hola Yuri."
    y "Hola."
    "Nos quedamos viendo durante unos segundos."
    "Esto es ridículo."
    "Nos besamos ayer."
    "¿Por qué estamos actuando como si fuera la primera vez que hablamos?"
    mc "Antes de que diga cualquier cosa..."
    "Levanto la pequeña bolsa."
    mc "Tengo algo para ti."
    y "¿Eh?"
    mc "Bueno..."
    mc "Técnicamente es de Natsuki."
    "Lo siento Nat pero no me llevaré tu crédito"
    y "¿Natsuki?"
    "Los ojos de Yuri se abren un poco."
    mc "Me la encontré por el camino."
    mc "Y me obligó a entregarte esto."
    y "..."
    "Yuri observa la galleta en forma de gato."
    "Por un momento parece completamente sorprendida."
    y "Ella sigue haciendo estas cosas..."
    "Su voz se vuelve más suave."
    y "Nunca cambia."
    "Me invita a pasar y entro"
    mc "¿Entonces no han hablado demasiado?"
    y "No en realidad, casi nada después de que dejamos el club"
    y "Nos peleábamos mucho pero sé que era una buena amiga, especialmente por las cosas como estas"
    mc "Sí, suena como a nuestra tsun local"
    mc "Yo también había hablado poco con Sayo hasta hoy, vino a emboscarme hace rato."
    y "¿Sayori fue a tu casa?"
    mc "Sí."
    mc "Y estuvo molestándome durante media hora."
    y "Eso suena como Sayori."
    "Yuri sonríe un poco."
    mc "También preguntó mucho por ti."
    y "¿Por mí?"
    mc "Claro."
    mc "Le alegró saber que estás mejor."
    "Yuri baja la vista hacia la galleta."
    y "Ya veo..."
    "Su voz suena extrañamente baja."
    mc "¿Pasa algo?"
    y "No es nada."
    "Parece pensarlo unos segundos."
    y "Supongo que me alegra."
    y "Solo que..."
    y "Mientras yo pude estar ahí"
    y "Ella lo estuvo."
    mc "Yuri..."
    y "No me malinterpretes."
    y "No estoy molesta."
    "Por un momento parece avergonzada de haber dicho eso."
    mc "Bueno."
    mc "Si te sirve de consuelo, Sayori me pego almenos dos veces."
    "Yuri deja escapar una pequeña risa."
    y "¿Es por eso que tienes ese moretón en la cabeza?"
    "¿UHH, en serio? Exterminaré las rocas"
    mc "Además..."
    mc "Ella estaba preocupada por ti."
    mc "Natsuki también."
    "Yuri observa nuevamente la galleta de gato."
    y "Quizás debería hablar con ellas."
    mc "Creo que les gustaría mucho eso."
    mc "También me habló sobre reunirnos de nuevo, dudo que rechacen algo así"
    "Un silencio aparece de la nada, después recuerdo a lo que vine"
    "No tiene sentido posponerlo, aquí vamos"
    mc "Yuri... sobre ayer, nosotros estamos... ya sabes"
    mc "¿Estamos saliendo?"
    "La pregunta parece sorprender a Yuri, no la culpo"
    y "Solo si tú quieres..."
    "Dice sonrojada"
    mc "¿Estás bromeando? Por supuesto"
    "Me levanto emocionado a abrazarla"
    "Ella me devuelve el abrazo."
    "Un poco torpemente."
    "Como si todavía no estuviera acostumbrada a algo así."
    "Por un momento ninguno de los dos dice nada."
    "Simplemente nos quedamos ahí."
    "Es extraño."
    "Hace unos meses probablemente habría pensado que algo así nunca podría pasar."
    y "[player]..."
    mc "¿Sí?"
    y "Todavía se siente un poco irreal."
    mc "¿Qué cosa?"
    y "...Todo esto."
    "Yuri desvía la mirada."
    y "Tú."
    y "Nosotros."
    "Una pequeña sonrisa aparece en mi rostro."
    mc "Créeme."
    mc "Yo tampoco esperaba terminar aquí."
    y "Ujuju..."
    "Yuri deja escapar una pequeña risa."
    "Creo que es la primera vez que la escucho reír tan tranquila."
    "Después de unos segundos finalmente nos separamos."
    mc "Bueno."
    mc "Ahora tengo una novia oficialmente."
    y "P-por favor no lo digas así..."
    "Su rostro se vuelve completamente rojo."
    mc "¿Por qué no?"
    y "Porque es vergonzoso..."
    mc "A mí me parece genial."
    "Yuri intenta ocultar su sonrisa."
    "Fracasa miserablemente."
    "Me dejo caer nuevamente en el sofá junto a ella."
    "Por un momento el silencio vuelve."
    "Pero esta vez ninguno parece incómodo."
    "Entonces recuerdo algo."
    mc "Oh, ¿entonces crees que deberíamos reunirnos de nuevo?"
    y "Hm?"
    "Yuri parpadea sorprendida."
    y "¿Reunirnos?"
    mc "Sí."
    mc "Tú, yo, Sayori y Natsuki."
    "Yuri guarda silencio unos segundos."
    y "Eso... suena agradable."
    mc "Yo pensé lo mismo."
    "Por primera vez en un tiempo, la idea de volver a reunirnos parece esperanzadora."
    mc "¿Qué tal si las llamamos ahora? Aún no es tan tarde"
    y "¿Ahora?... Está bien hagámoslo"
    "Tomo mi celular y le marco a nuestra tsundere favorita"
    "Responde en unos segundos"
    n "¿Ahora qué, (player)?"
    mc "Buenas noches a ti también Nat"
    mc "Oye, ¿te gustaría reunirnos de nuevo? Ya sabes, tú, yo, Sayo, Yuri"
    n "Bueno tengo un tiempo sin verlas, iré"
    "poco tiempo después nos ponemos de acuerdo acerca de cuando y donde, Yuri y ella se despiden"
    mc "Diría que te toca convencer a Sayori."
    y "¿Convencerla?"
    mc "Tienes razón."
    mc "Ni siquiera va a dejarme terminar la frase."
    "Yuri ríe por eso"
    mc "Hola sayo, ¿recuerdas lo que dijiste hace rato sobre reunirnos? Yuri y Nat están de acuerdo"
    s "¿EN SERIOOOOO?"
    s "Iré"
    mc "Espera, aún ni siquiera sabes cuándo"
    s "¿Cuándo?"
    mc "El viernes, mi casa"
    s "No necesito saber más, chao (player)"
    "Sayori cuelga"
    mc "Qué difícil fue convencer a Sayori"
    y "Así es ella"
    mc "Yo también tengo que regresar a casa Yuri"
    "Yuri me acompaña a su puerta"
    mc "Nos vemos Yuri"
    y "Adios (player)"
    "Ella me abraza y se lo devuelvo"
    "Después regreso a casa"
    # Cambio de escena a habitación de me
    "*PIP PIP*"
    mc "Maldita alarma"
    "Me preparo para iniciar el día"
    "Veo de reojo mi consola de videojuegos"
    mc "Algún día volveré a tener tiempo para ti amigo"
    "Bajo a la cocina a desayunar algunas tostadas y café negro"
    mc "Muy bien, creo que tengo tiempo para correr de nuevo"
    "Cuando apenas me iba a preparar para salir escucho mi timbre"
    mc "Si es Sayori me sorprenderá que esté despierta ahora"
    "Camino y abro la puerta"
    s "Holaa (Player)"
    mc "Honestamente esta vez dudé que fueras tú, es muy temprano"
    s "Quería ayudar a mi mamá a limpiar mi casa hoy, y nos sobró tiempo."
    mc "¿Wow, quién eres y qué le hiciste a mi Sayori?"
    "Sayori entra a la casa sin esperar invitación."
    mc "¿Sabes? Normalmente la gente espera a que la inviten."
    s "Demasiado tarde."
    "Se deja caer en el sofá como si viviera aquí."
    mc "Buenos días para ti también."
    s "Buenos días."
    "Por un momento parece buscar algo que decir."
    s "Estoy emocionada por la reunión."
    mc "Se notó por el grito de ayer."
    s "¡Era un grito completamente normal!"
    mc "Creo que vi volar algunos pájaros cuando sonó."
    "Sayori me saca la lengua."
    s "Oye..."
    "Su tono cambia un poco."
    s "¿Puedo preguntarte algo?"
    mc "Eso depende de qué tan peligroso sea."
    s "¿Y si invitamos a Monika?"
    ""
    "Ah."
    "Sabía que algo raro estaba pasando."
    mc "No."
    s "Ni siquiera lo pensaste."
    mc "No."
    s "(Player)..."
    mc "Sayori."
    "Ella suspira."
    s "Sé que estás enojado."
    mc "No estoy enojado."
    "Pausa."
    mc "Bueno, sí."
    s "Lo sabía."
    mc "Lo que hizo estuvo terrible."
    mc "Y Yuri fue quien terminó pagándolo."
    s "Lo sé."
    "Su respuesta llega tan rápido que me sorprende."
    s "No estoy diciendo que lo que hizo estuvo bien."
    s "Solo digo que..."
    s "Monika tampoco ha estado bien desde entonces."
    "Frunzo el ceño."
    mc "¿A qué te refieres?"
    s "Ha estado concentrándose en la escuela y está yendo a terapias."
    s "Apenas y puede seguir."
    s "Está demasiado estresada."
    s "Creo que necesita tranquilizarse un poco."
    "Eso no cambia lo que pasó."
    s "No tienes que perdonarla hoy."
    s "Ni mañana."
    s "Solo... piénsalo."
    "Sayori se pone de pie."
    s "Bueno."
    s "Ya cumplí mi misión."
    mc "¿Misión?"
    s "Sí."
    s "Ahora me iré antes de que me rechaces otra vez."
    mc "No prometí nada."
    s "Lo sé."
    "Ella sonríe."
    s "Nos vemos el viernes."
    "Y después se marcha."
    "Cierro la puerta."
    "En un instante la casa vuelve a quedar en silencio."
    "Monika."
    "No estaba seguro de querer pensar en ella."
    "Pero ahora no puedo quitármela de la cabeza."
    "Si está yendo a terapia significa que se arrepiente, ¿no?"
    "Aun así eso no cambia lo que hizo"
    "Debería preguntarle a Yuri"
    "Saco mi teléfono y le marco"
    mc "Buenos días Yuri, ¿cómo estás?"
    y "Buenos días (player), me siento muy bien, ¿y tú?"
    "Eso me hace sonreír"
    mc "También estoy bien Yuri, oye Sayori vino a invadirme de nuevo y me dijo algo"
    mc "Quería que invitáramos a Monika, me contó que lo ha pasado mal y está yendo a terapia"
    mc "Supongo que se arrepiente pero aun estoy molesto con ella y eso no cambia las cosas"
    mc "¿Tú qué piensas?"
    y "Creo que si ella tiene intención debemos darle una segunda oportunidad"
    y "Después de todo yo sé exactamente lo que se siente perder el control"
    mc "..."
    "Yo honestamente aún desconfío de esto pero sé que Yuri está haciendo lo correcto"
    "Ademas también soy un cursi que cree en las segundas oportunidades"
    mc "Si le tienes fe, entonces no perderíamos nada intentándolo"
    y "¿Estás seguro?"
    mc "No."
    mc "Para nada."
    mc "Pero tampoco quiero quedarme preguntándome qué habría pasado si la invitábamos."
    y "..."
    y "Gracias."
    mc "No me agradezcas todavía."
    mc "Si intenta algo raro, Natsuki la lanzará por una ventana."
    y "¡[player]!"
    mc "Estoy bromeando."
    y "..."
    mc "Más o menos."
    mc "Está bien Yuri, nos vemos luego"
    y "Adiós (player) cuídate"
    "Cuelgo la llamada"
    "Miro la lista de contactos."
    "Mi dedo se detiene sobre un nombre."
    "Hace unos días jamás habría pensado en llamarla."
    "Y honestamente..."
    "Todavía no estoy seguro de querer hacerlo."
    "Ring..."
    "Ring..."
    "Ring..."
    # TODO: guion inconcluso - falta escribir la resolucion de esta llamada a Monika
    # y el resto de la ruta buena a partir de aqui. Se dejo un final seguro (return)
    # para que el juego no truene si se llega a este punto durante pruebas.
    pause 1.0
    return
