label cap3:
    # Definimos la animación para los párpados
    scene bg yuri_bedroom 
    with dissolve_scene_full
    show expression Solid("#000000") as parpados at despertar_ojos
    $ renpy.pause(4.9, hard=True)
    "Lentamente abro mis ojos"
    "La cálida luz del sol se asoma a través de las cortinas"
    "Al principio me sorprendió cuando Yuri ofreció compartir una cama, pero pronto descubrí porque ella no estaba nerviosa"
    "Ella no estaba mintiendo cuando dijo que tenía una cama grande"
    "Esta cosa tiene casi dos metros de ancho"
    show yuri turned casual rup lup cm ce zorder 2 at t11
    "Echo un vistazo para ver a Yuri dormir tranquilamente"
    "Durante las ultimas dos semanas hemos estado tomando turnos en la casa del otro para
    leer, tomar té y demás cosas"
    "Hemos avanzado mucho el libro que leiamos juntos, estamos cerca de los últimos capítulos del libro"
    show yuri turned casual rup lup cm ce zorder 2 at thide
    hide yuri 
    "No hemos ido al Club de literatura en absoluto; De hecho estoy muy seguro que el Club ha sido
    clausurado desde que solo están Sayori y Monika"
    "Incluso envuelto en gruesas cobijas, tengo frio"
    "Sayori amaba el Club de literatura, y probablemente ya este clausurado"
    "Sayori"
    "¿Como estara Sayori?"
    show yuri turned casual me e1e b3c zorder 2 at t11
    y "[player]..."
    mc "Buenos días, dormiste bien?"
    y turned casual lup rup lsur cm ce "Si… siento que necesitaba algo asi"
    "A pesar de acabar de despertar, Yuri todavia parece agotada por todo lo ocurrido."
    "Supongo que tecnicamente, con la excepción de compartir una cama, nuestra relación no ha progresado más alla de ser solo amigos"
    "Aun asi me alegra mucho que este en paz…o almenos por ahora"
    y turned lsur om oe "¿Qué estas pensando?"
    mc "¿Eh?"
    y turned rdown ldown "Estabas distraido. ¿Tienes algo en mente?"
    mc "Estoy bien, solo necesito refrescarme"
    
    "Me levanto de la cama y me dirijo al baño para hacer mi rutina normal"
    show yuri zorder 2 at thide
    hide yuri  
    "Veo como Yuri sale de la habitación antes de entrar al baño"
    #escena en el baño
    scene bg yuri_bathroom
    with wipeleft_scene
    "Han sido unos dias increibles no entiendo la imagen que veo en el espejo"
    "Unas enormes y profundas ojeras se apoderan de mi rostro."
    "Sin darle mayor importancia, me arrojé un poco de agua fría en la cara y cepillé mis dientes."
    "Estoy un poco intranquilo, el club no volvio a ser lo mismo desde el dia que Monika y Yuri discutieron"
    "Me preocupa principalmente Sayori, sé que era un lugar importante para ella"
    play sound ducha fadein 0.5
    "Abro la llave para llenar la tina y tomar un baño"
    "Un baño caliente me tranquilizara un poco, seguro todo esta bien"
    
    window hide 
    #Toma el baño escena por 4 o 5 segundos mientras se baña
    $ renpy.pause(6, hard=True)
    window show
    "Enciendo la lavaropa y me coloco ropa comoda que traje conmigo"
    scene bg kitchen
    with wipeleft_scene
    show yuri turned casual happ zorder 2 at t11
    "Una vez abajo, veo que Yuri ha comenzado a preparar el desayuno"
    mc "¿Qué estas haciendo?"
    show yuri turned casual rup happ om oe zorder 2 at t11
    y "Solo unos panqueques"
    mc "Huelen delicioso"
    "Le lanzo una leve sonrisa a Yuri."
    show yuri turned happ cm ce

    "Ella me envía una de vuelta y continua cocinando."
    show yuri zorder 2 at thide
    hide yuri 
    "Tomo asiento, y me sumerjo en mis pensamientos"
    "mi cabeza sigue sin creer lo que ha pasado en las últimas dos semanas."
    "Pasar tanto tiempo junto a Yuri , dormir en su cama, cocinar juntos"
    "Parecemos una autentica pareja"
    "No todo ha sido perfecto, pero no puedo quejarme"
    "He tratado de hablar con Yuri sobre el elefante en la habitación"
    "Evitó el tema cada vez que intente mencionarlo"
    "tenemos que hablar sobre sus lesiones."
    "Yuri es muy reservada y planee esperar a que ella se abriera a mi, pero no ha sido el caso."
    "Me he estado preparando para cuando ella lo haga, y proponer algunas ideas pero nunca paso."
    "Contacte a un psicólogo que pueda ayudarla, y tal vez incluso prescribirla con
    medicamentos."
    show yuri turned casual rup happ zorder 2 at t11
    "Yuri llega a la mesa con dos platos de panqueques" 
    "deja un plato frente a mi, y luego toma asiento."
    y turned casual rdown happ cm ce "¿Tenías algún plan hoy, [player]?"
    "Es ahora o nunca."
    y "¿Involucraban la lectura o el té?"
    "Yuri sonríe enigmáticamente pero no comparto su momento de felicidad."
    mc "Yuri tenemos que hablar de las heridas en tu brazo"
    show yuri turned casual lsur om oe 
    mc "Me preocupa que te estés haciendo daño a ti misma para lidiar con lo que sientes"
    mc "Hay maneras mucho mas sanas de lidiar con tus emociones"
    mc "Estuve investigando alternativas y tecnicas para controlar el deseo de hacerlo"
    mc "yuri puedes salir de esto"
    show yuri turned casual n2 pani om oe zorder 2 at h11
    "Yuri salta, tirando su silla al suelo."
    y turned casual n1 sad om oe "¿Por qué… por qué me harías esto?"
    "Puedo ver el miedo en sus ojos."
    show yuri turned casual sad zorder 2 at s11
    "Ella empieza a retroceder "
    " Instintivamente quiero acercarme… pero me detengo.."
    mc "oye..."
    show yuri shy casual sad om ce zorder 2 at t11
    "Ella se para frente a mi con una mirada de inmenso dolor en su rostro"
    mc "Yuri, por favor mirame."
    show yuri shy casual cm oe 
    mc "Te prometí que te ayudaría."
    mc "Y no planeo romper esa promesa."
    y shy casual om oe "[player], no creo que pueda."
    mc "No digas eso, Yuri."
    mc "Este hombre puede ser la respuesta que hemos estado buscando."
    mc "Él puede ayudarte a comprenderte a ti misma y tal vez incluso a ayudarte con tus… ya sabes."
    show yuri shy neut cm oe
    "Ella mira al suelo por lo que parece una eternidad"
    mc "Estuve investigando sobre terapia y tambien es una buena opcion"
    mc "Encontre un consultorio cerca del centro a donde podriamos ir"
    show yuri turned casual rup lup sad cm ce zorder 2 at s11
    pause 0.5
    y "(inhalación)"
    y turned casual sad om oe "Okay"
    mc "¿Okay?"
    y "Okey, iré a ver al psicólogo"
    "Mi corazón da un salto de emoción"
    show yuri casual sad cm oe
    mc "¡Eso es genial!"
    "La abrazo con emocion, pero ella no puede hacer lo mismo"
    "La suelto"
    mc "Lo llamaré y veré cuando podemos programar una cita"
    y "..."
    "Es obvio que ella no está particularmente entusiasmada por esto."
    "He estado cerca de ella todo este tiempo y aun así me ha mantenido al margen de la mayoría de sus sentimientos."
    "No puedo imaginar cómo reaccionará teniendo que abrirse con un completo desconocido."
    "Una pequeña duda atraviesa mi mente..."
    "(¿De verdad quiere hacer esto o solo intenta tranquilizarme?)"
    y turned flus om oe "Deberíamos seguir comiendo antes de que se enfríe."
    mc "Oh... sí, claro."
    show yuri turned casual flus cm oe
    "Nos sentamos nuevamente y cada uno vuelve a su plato."
    "Levanto la vista hacia Yuri y noto un leve temblor en sus manos."
    "Las mangas de su suéter cuelgan flojamente, dejando entrever parte de sus brazos."
    "Por un instante, alcanzo a distinguir finas cicatrices alineadas sobre su piel."
    "No sé si estoy haciendolo bien… pero no voy a dejarte sola con todo esto Yuri."
    scene bg kitchen
    with wipeleft_scene
    show yuri turned casual n2 mj e1c b1b zorder 2 at t11
    "Yuri parece haber perdido el apetito; puedo verla simplemente jugando con sus panqueques."
    mc "Yuri, ¿estás bien? ¿No tienes hambre?"
    y turned casual sad cm oe "N-No es nada, solo me distraje..."
    "Yuri empieza a comer sus panqueques."
    "Con cada bocado parece estar forzándose a tragar; será mejor que no diga nada al respecto."
    show yuri turned casual n1 mg e1d b1c zorder 2 at t11
    mc "Yuri, respecto a los planes de hoy..."
    y "¿Sí...?"
    mc "¿Qué te parece si tomamos un poco de aire después de que terminemos de desayunar?"
    y turned lsur om oe "Está bien, pero... ¿a dónde iremos?"
    mc "Podríamos ir a caminar por la plaza y visitar algunas tiendas."
    y turned happ om oe "Suena como una excelente idea."
    mc "También podríamos aprovechar para comprar comida y demás cosas para la casa."
    y turned happ om ce "Por supuesto, la despensa está un poco vacía."
    "Yuri y yo comemos tranquilamente en silencio hasta terminar nuestros platos."
    "me levanto de la mesa"
    show yuri turned casual mg e1d b1c zorder 2 at t11
    mc "Yuri, dame tu plato."
    mc "Si necesitas prepararte para ir a la plaza, ve tranquila."
    mc "Yo lavaré los platos mientras tanto."
    y turned mla e4b b1c "Muchas gracias, [player]. No me tardo."
    "Mientras lavo los platos, escucho cómo Yuri sube las escaleras."
    scene bg yuri_sala
    with wiperight_scene
    play music street_stroll fadein 0.5
    "Han pasado un par de minutos desde que terminé de lavar los platos."
    "Decidí no apresurar a Yuri"
    "Las chicas suelen tardar un poco en prepararse para salir, ¿no?"
    "Escucho sus pasos y veo a Yuri bajar las escaleras."
    show yuri turned casual rup lup ma e2e b1c zorder 2 at t11 
    "Mis ojos se quedan completamente hipnotizados."
    mc "Yuri, te ves... {w=1}preciosa."
    y turned n3 mk e2b b1a "[player]... n-no es para tanto."
    y turned mg e1a b1a "Creo que ya estamos listos para salir."
    y turned ldown rdown n1 mg e1a b1f "¿[player]?"
    mc "Oh, lo siento, aún sigo un poco boquiabierto al verte."
    show yuri turned casual happ om ce zorder 2 at t11 
    mc "Por supuesto, vámonos."
    #La escena cambia hasta el centro de la ciudad.
    scene bg city_street
    with wipeleft_scene
    show yuri turned casual happ om oe zorder 2 at t11
    y "[player]... ¿te molestaría entrar aquí?"
    "Miro el cartel sobre el local."
    "Es una tienda de ropa."
    mc "Sí, claro."
    "Abro la puerta y dejo pasar a Yuri primero."
    scene bg clothing_store
    with wipeleft_scene
    "Una vez dentro, busco un banco donde sentarme."
    "Nunca me gustaron demasiado las compras."
    "A menos que sea para comprar videojuegos."
    show yuri turned casual happ om oe zorder 2 at t11
    mc "¿Sabes qué estás buscando?"
    y "Oh... pensaba que podríamos simplemente mirar un poco."
    mc "¿Mirar?"
    "¿Qué tienen las mujeres con eso?"
    "¿Por qué entrarías a una tienda de ropa solo para mirar?"
    mc "Bueno... está bien."
    show yuri turned casual happ om oe zorder 2 at thide 
    hide yuri
    "Yuri comienza a revisar los estantes mientras yo permanezco sentado sin nada que hacer."
    "Miro los pósters pegados en las paredes."
    "Todos muestran modelos atractivos posando dramáticamente con ropa elegante."
    y "[player], ¿viste algo que te guste?"
    "La voz de Yuri llega desde el otro lado del estante."
    mc "Ummm…"
    "Examino rapidamente algunas prendas."
    "Mis ojos se detienen en un vestido de verano."
    "Me acerco y lo saco del perchero."
    "Es un vestido largo color magenta, de tela ligera y tirantes finos."
    "Mientras lo observo, un chico aparece detrás de mí."
    "chico" "Oye, ese es morado."
    "chico" "Es su color favorito."
    "El chico toma el vestido directamente de mis manos y se dirige a la caja para comprarlo."
    mc "Bueno... supongo que eso pasó."
    show yuri casual turned rup ma e1d b1a zorder 2 at t11
    "Camino hacia el mostrador donde Yuri recibe una bolsa del cajero."
    mc "¿Qué compraste?"
    y casual turned mb e1d b1a "Solo... algo para mí."
    "El rugido de mi estómago rompe el silencio."
    "Yuri me mira."
    mc "¿Quieres ir a comer a algún lugar?"
    y casual turned happ om ce "Por supuesto."
    "Yuri termina de pagar y sonríe suavemente mientras salimos de la tienda."
    show bg city_street
    with wipeleft_scene
    show yuri casual turned happ cm oe zorder 2 at t11
    mc "Muy bien, Yuri. ¿Dónde quieres ir a comer?"
    y casual turned happ om ce "[player], no es muy caballeroso hacer que una dama elija."
    mc "Ahhh..."
    y casual turned rup lup "Jujuju."
    y casual turned rdown ldown "Lo siento... pensé que sería divertido molestarte."
    "Yuri continua riéndose de mi."
    "Es increíble lo cercana que se ha vuelto a mi."
    "Según todos los demás, ella suele mantenerse alejada de la gente."
    "Aunque, claro..."
    "Probablemente la mayoría no irrumpe en su casa."
    "De cualquier forma, verla reír hace que todo esto valga la pena."
    mc "Sí, sí."
    mc "Ya te divertiste suficiente."
    mc "¿No tienes un lugar o algo en especifico que quieras comer?"
    y casual turned mb e1d b2a "¿Qué tal si vamos a un restaurante de ramen?"
    "La miro con curiosidad."
    mc "¿No puedes comprar ramen por menos de un euro en el supermercado?"
    y casual turned mg e1a b1c "Eso es el ramen instantáneo que compras tú..."
    y casual turned b1f "¿No me digas que nunca has probado un buen ramen auténtico?"
    mc "No puedo decir que lo haya hecho."
    y casual turned lup mh e1d b1c "¿Crees que haya algún restaurante cerca?"
    mc "Seguro encontramos uno."
    "Saco mi teléfono y comienzo a buscar restaurantes cercanos."
    "Después de unos segundos encuentro uno a pocas cuadras."
    mc "Hay uno muy cerca de aqui con muy buenas calificaciones."
    mc "Mi teléfono está por quedarse sin batería. ¿Puedes buscar la dirección en el tuyo?"
    y casual turned mg e1b b1a "Claro. ¿Cuál es?"
    mc "1273 Calle Tomorrow."
    y casual turned mla e1d b1c "Ya lo encontré."
    mc "Entonces guía el camino."
    show yuri casual turned mla e1d b1c zorder 2 at thide 
    hide yuri 
    "Caminamos juntos por las calles del centro."
    "El clima es agradable."
    "El bullicio habitual de la ciudad llena el ambiente."
    "La gente pasea de un lado a otro, probablemente disfrutando del fin de semana igual que nosotros."
    "Un hombre de mediana edad parece estar haciendo un escandalo parado en medio de la acera."
    "Lleva una camisa rosa claro con pantalones cortos a juego, cinturón negro y zapatos marrones."
    "Tiene las manos apoyadas sobre el abdomen y una sonrisa inquietante."
    "Yuri y yo pasamos rápidamente junto a él esperando que no diga nada."
    "Unos minutos después llegamos al restaurante."
    "Miro el letrero."
    "Spaghetto's Bowl."
    mc "Aquí es."
    "Mantengo la puerta abierta para Yuri y entramos."
    show bg cafe
    with wipeleft_scene
    mc "Hace frio aquí."
    "Tan pronto como entramos, una ráfaga de viento sopla contra mi cuerpo."
    "Este lugar definitivamente mantiene su aire acondicionado encendido."
    "Estiro mi cuello hacia adelante, más allá de la barra donde está la cocina."
    "Todos los cocineros se ciernen sobre ollas grandes que supongo que tienen están llenas de fideos."
    "La anfitriona se acerca a nosotros."
    anf "Hola, ¿Cuantos hoy?"
    mc "Dos por favor."
    anf "Justo por aquí."
    "Seguimos a la anfitriona hasta una mesa y nos sentamos."
    anf "Su camarero estará con usted en breve."
    "Ella nos entrega los menús y se retira para sentar a los proximos clientes."
    mc "Esto es realmente agradable Yuri."
    y "Supongo que nunca has estado en un restaurante de fideos antes, [player]."
    mc "Bueno...sí."
    "Esta bastante bien por aquí."
    "Miro alrededor del lugar."
    "La iluminación tenue y la música crean el ambiente ideal para comer fideos."
    "Miro el menú."
    "Hay mucha variedad teniendo en cuenta mis puntos de vista anteriores sobre el ramen."
    mc "¿Qué vas a pedir?"
    y "Lo más probable es el Tonkatsu."
    mc "¿Te gusta la carne de cerdo?"
    y "¿Qué quieres decir?"
    mc "Uhh... solo asumi."
    "Uh oh."
    y "¿Qué una mujer no comeria carne de cerdo?"
    "No estoy seguro de si es la cocina, pero mi cara esta cada vez más caliente."
    mc "No-no quise decir ninguna ofensa, yo-."
    y "Ujujuju."
    "Eres fácil de burlar, [player]."
    "Pongo los ojos en ella."
    mc "Ok, me engañaste, muy graciosa."
    "Fue bastante divertido para ser honesto."
    "Vuelvo a leer el menú."
    mc "Creo que pediré lo mismo."
    y "Una buena elección, [player]."
    "La camarera llega a nuestra mesa"
    "Ella coloca dos vasos de agua delante de nosotros."
    cam "¿Qué les puedo ofrecer a ustedes dos?"
    mc "Una orden de Tonkatsu."
    "Ella gabaratea en su libreta de notas."
    cam "¿Y para usted, señorita?"
    y "Uhhh..."
    "Yuri comienza a ponerse nerviosa."
    "Ella tiene el mismo aspecto que tenia en la cafetería."
    y "Quiero lo mismo."
    "Mis ojos se abren un poco mientras observo a Yuri."
    "La camarera, ajena a la situación, escribe las ordenes."
    y "Few...."
    cam "Eso sera todo"
    mc "Sí."
    "Ella toma los menús y luego deja nuestra mesa."
    y "¿Está todo bien?"
    "Siento la saliva en mi garganta."
    mc "Simplemente no esperaba que ordenaras."
    "Yuri sonríe tímidamente."
    y "Bien..."
    "Supongo que cuando estoy cerca de ti me siento un poco más cómoda siendo yo misma."
    "Le doy otra sonrisa y ella me devuelve una."
    "Eso en si mismo es una pequeña victoria."
    "La camarera regresa, tazones en mano."
    cam "Disfruten su comida."
    "Con una rápida reverencia, ella se aleja."
    mc "¿Qué de esto?"
    "Con mis palillos, señalo un tazón pequeño de mezcla roja."
    y "Es una especia que puedes poner en tu ramen."
    mc "Oh, bien."
    "Agarro el tazón pequeño y empiezo a meterlo en mi comida."
    y "¡[player], espera!"
    mc "¿Qué?"
    y "Esta muy picante. Se supone que solo debes poner una pequeña cantidad."
    "Por eso viene una porción tan pequeña."
    mc "Estoy seguro de que estaré bien."
    "Después de sacar la mitad del tazón, lo puse de nuevo y resolví los fideos con mis palillos."
    "Agarro un palillo lleno de fideos y lo meto en mi boca."
    "Yuri se estremece tan pronto como los fideos entran en la boca."
    mc "No es tan mal-"
    mc "¡Oh por Dios!!!"
    mc "¡Oh mierda!"
    mc "Oh Dios, oh Dios."
    "Empiezo a respirar pesadamente."
    "El humo empieza a salir de mi boca como un chimenea."
    "Me siento tan acalorado"
    "Estoy sudando a lo largo de mi frente."
    "El caldo se siente como lava fundida que se vierte por mi esófago."
    mc "¿Quién hizo esto, Satanas?"
    "Gotas de sudor caen por mi cara."
    "¿O son esas lagrimas?"
    "De cualquier manera me arde la boca."
    "Agarro mi agua y la trago."
    "El ardor se desvanece."
    mc "¡Rayos!"
    y "¿Estás bien?"
    mc "Ve el lado positivo, mi nariz nunca ha estado tan descongestionada en años."
    y "Ujuju."
    "Compartimos unas risas y continuamos nuestras comidas."
    "Más tarde, el escenario se transporta a la entrada de la casa de Yuri"
    y "¿[player]?"
    mc "¿Sf?"
    y "Gracias a ti."
    "Por todo."
    mc "Solo era el almuerzo."
    y "No."
    "No me refiero al restaurante de fideos."
    "Me refiero a... Todo."
    "Todo lo que has hecho."
    "Realmente no he sentido que he hecho mucho"
    "Pero cuando pienso en ellos, Yuri probablemente nunca ha tenido un día en el que salga como un"
    "amigo."
    "Solo una persona que esté con ella probablemente significa todo para ella."
    mc "Está bien Yuri."
    "Como dije, los amigos se mantienen juntos."
    "Ella toma su mano y la entrelaza con la mia."
    "Es suave, pero apretada."
    y "¿Crees que todavía puedo mejorar, (Jugador)?"
    "Simplemente le sonrío."
    "La miro fijamente a sus ojos color lavanda."
    mc "No creo que seas alguien rota."
    mc "Creo que eres alguien cansada de sentirse así."
    mc "Y quiero ayudarte mientras intentas salir de eso." 
    "Veo una lagrima deslizarse por su rostro."
    "Ella toma un momento para absorber mi declaración."
    y "Nos vemos luego, [player]."
    mc "Que tengas buena noche, Yuri."
    "Yuri se separa y entra a su casa."
    "Por un momento me quedo allí solo mientras la fresca brisa del invierno me encapsula."
    "Mis propias palabras corren repetidamente por mi mente."
    mc "(En voz baja) No sé como, pero lo superaremos."
    # "Unos días después"
    "Hoy he despertado en mi propia cama."
    "No leímos la ultima noche juntos, así que ella está sola en su casa."
    "En realidad, nuestras conversaciones durante esta semana han sido... mínimas."
    "Algunos mensajes cortos."
    "Respuestas tardías."
    "Excusas para terminar rápido las conversaciones."
    "Desde que mencioné la idea de buscar ayuda profesional, Yuri se ha sentido más distante."
    "Yuri se ve a si misma como una especie de loca, y quiero creer que un psiquiatra le ayudara a"
    "quitarse esa imagen."
    "De igual forma, esto es importante, le recorde a Yuri por mensaje que después de la escuela"
    "deberíamos ir."
    "Miro afuera en mi ventana."
    "Esta un poco nublado, pero eso no va a pararme"
    "Continuo mi aburrida rutina de bañarme, cepillar mis dientes y vestirme."
    "Me dirijo a la cocina."
    mc "Que como... ¿Qué como?"
    "Abro y cierro varios gabinetes una y otra vez, descartando comidas que no sean desayuno."
    mc "Oh"
    mc "¡Entonces será cereal!"
    "Lleno un tazón de cereal de maíz."
    "Abro suavemente el refrigerador."
    mc "No, no, no no, no..."
    "Ya no tengo leche."
    "Este es el peor día de mi vida."
    "Tal vez pueda encontrar un substituto."
    "Miro entre lo más profundo de la nevera."
    "Un envase de jugo de naranja."
    "Miro de nuevo al tazón."
    "Miro al jugo de naranja."
    "Miro de nuevo al tazón."
    mc "Esto es horrible, pero no hay de otra."
    "Señor, perdoname por esta aberracion culinaria."
    # "Transportamos el escenario a un salón de clases"
    "La ultima clase casi termina."
    "Miro el reloj de la pared."
    "Nunca pensé que una hora pudiera sentirse tan larga."
    "Ni siquiera estoy escuchando al profesor."
    "Mi cabeza sigue regresando al mismo pensamiento."
    "¿Y si Yuri se arrepiente?"
    "¿Y si dejo las cosas peor?"
    "La campana suena."
    mc "Tomo un atajo entre el patio para ir a verme con Yuri."
    "Mi mente esta quemándose ahora mismo."
    "Aún tengo dudas de lo que pueda pasar si llevo a Yuri con un profesional."
    mc "Tomo un atajo entre el patio para ir a verme con Yuri."
    "Mi mente está completamente ocupada."
    "???" "¡[player]!"
    "Me detengo al escuchar mi nombre."
    "Esa voz..."
    "Me giro lentamente."
    mc "...Monika."
    m "Hola."
    "La saludo por simple educacion."
    mc "Hola."
    mc "Ya te ibas?"
    m "Si..."
    m "En realidad..."
    "Juega distraidamente con la manga de su uniforme."
    m "¿Podemos hablar un momento?"
    "No esperaba escuchar eso."
    "Despues de todo lo que paso en el club, pense que evitaria acercarse a mi."
    "Y, siendo sincero..."
    "Yo tampoco tenia muchas ganas de hablar con ella."
    mc "Lo siento."
    mc "Tengo algo importante que hacer."
    m "No tardare mucho."
    "Hago un pequeño silencio."
    "En la distancia alcanzo a distinguir una figura de cabello morado cerca de la salida."
    "Yuri."
    "Seguramente esta esperandome."
    mc "De que querias hablar?"
    m "baja un poco la mirada."
    "Durante unos segundos parece buscar las palabras."
    m "He estado pensando bastante desde lo del club."
    m "Se que probablemente ninguno de ustedes quiera verme."
    m "Y..."
    m "Supongo que lo entiendo."
    "Honestamente no esperaba escuchar eso."
    m "Solo queria decir que..."
    m "...nunca quise que terminaramos de esta forma."
    "La miro unos segundos."
    "No parece estar intentando convencerme de nada."
    "Simplemente se ve cansada."
    mc "Nunca pense que quisieras destruir el club."
    "Monika levanta ligeramente la vista."
    mc "Pero eso fue lo que termino pasando."
    "El silencio que sigue se siente mucho mas largo"
    "Monika baja lentamente la cabeza."
    m "...Supongo que si."
    "Por un momento ninguno de los dos dice nada."
    m "respira profundamente."
    m "Aun asi.."
    m "Sigo creyendo que habia cosas que no estaban bien."
    m "Solo..."
    "Duda."
    m "...creo que no supe como decirlas."
    "Sus palabras suenan mucho menos seguras que antes."
    "Como si ni ella misma se lo creyera"
    "Miro nuevamente hacia la salida."
    "Yuri sigue esperandome."
    mc "Tengo que irme."
    m "asiente despacio."
    m "Si."
    m "No quiero retrasarte."
    "Empiezo a caminar."
    "Despues de unos pasos..."
    m "¿(Jugador)?"
    "Me detengo."
    m "Espero que Yuri este bien."
    "Sorprendentemente."
    "Suena sincera."
    mc "... Yo tambien."
    "Continuo caminando."
    "Despues de unos segundos, ya no puedo escuchar sus pasos detras de mi."
    # POV Monika
    "Me quedo inmovil observando como (player) se aleja."
    ""
    "No salio como esperaba."
    "Ni siquiera se que esperaba."
    "Bajo lentamente la mirada."
    m "Destrui el club..."
    "Ese pensamiento sigue dando vueltas dentro de mi cabeza."
    "No..."
    "Yo solo queria ayudar."
    "... Verdad?"
    "Comienzo a caminar sin una direccion clara."
    "El patio de la escuela esta casi vacio a esta hora."
    "Todo se siente extrañamente silencioso."
    unk "¿Monika?"
    "Levanto la vista."
    "Sayori."
    s "Pense que ya te habias ido."
    m "Si..."
    m "Solo estaba..."
    "No termino la frase."
    "Sayori me observa unos segundos."
    "Con preocupacion."
    s "¿Hablaste con (player)?"
    "asiento levemente."
    s "Como salio?"
    "..."
    m "...No muy bien."
    s "guarda silencio."
    "Despues se sienta en una banca cercama."
    s "Puedo decirte algo?"
    m "...Claro."
    s "sonrie con tristeza."
    s "Creo que tu si querias ayudar."
    "Mis ojos se abren un poco."
    s "Nunca pense que quisieras hacer daño."
    "Desvio la mirada."
    m "...Entonces, por que salio todo tan mal?"
    s "permanece pensativa unos segundos."
    s "Porque a veces las cosas no salen como esperas"
    s "Si, fuiste algo impulsiva antes."
    s "Pero siempre habrá oportunidad de mejorar"
    s "Es lo mejor que podemos hacer cuando tropezamos."
    "El viento mueve suavemente los árboles."
    "Ninguna de las dos habla durante unos segundos."
    m "...No se si todavia pueda arreglar algo."
    "Sayori sonrie con la misma calidez de siempre."
    s "No lo se."
    s "Pero creo que empezar a hacer las cosas diferente..."
    s "...es mejor que no intentarlo."
    "La observo."
    "No responde como esperaba."
    "Solo me recordó que todavia puedo decidir quien soy"
    "Quiza no pueda cambiar lo que hice."
    "Pero todavia puedo cambiar la forma en la que actuare ahora."
    "Debo intentarlo."
    "Incluso si nadie me perdona."
    "Es lo minimo que puedo hacer."
    # CAMBIO DE POV DE VUELTA AMC #Cambiamos de escena y nos encontramos a Yuri más
    "cerca de la salida."
    "Puedo notar como Yuri evita hacer contacto visual conmigo, parece incomoda por algo."
    "Me acerco, preocupado."
    mc "¿Yuri? ¿Está todo bien?"
    "Yuri se prepara antes de hablar, parece dudar antes de hablar."
    "Finalmente dice:"
    y "¿Has estado con Monika?"
    "Su voz suena en un tono mucho más bajo de lo normal."
    "Supongo que esta nerviosa y preocupada."
    "Como no estarlo?"
    "Después de todo, aun no supera del todo lo ocurrido en el Club, pese a que ya paso un tiempo."
    mc "Sí, hablamos un poco... Pero te prometo que no te tienes que preocupar por eso ahora."
    "Ella levanta la mirada."
    "Sus ojos reflejan inseguridad."
    y "N-no pelearon por mi culpa, ¿Verdad?"
    "Yuri lo pregunta como si cada palabra le pesara demasiado."
    "Evita mirarme directamente."
    mc "Yuri..."
    "Tardo unos segundos en responder."
    mc "No creo que seas la culpable de esto."
    mc "Las cosas entre Monika y yo ya estaban mal desde antes."
    y "¿De verdad...?"
    mc "Sí..."
    "Las palabras de Monika todavía siguen dando vueltas en mi cabeza."
    "Pero cuando veo a Yuri así de nerviosa, lo único que quiero es evitar que siga culpándose."
    mc "No hiciste nada malo por sentirte mal, Yuri."
    mc "tampoco tienes que cargar con todo esto sola."
    "Yuri baja lentamente la mirada."
    "Sus hombros dejan de verse tan tensos."
    "Como si por fin pudiera respirar un poco mejor."
    "Tras decir eso, Yuri empieza respirar más lento."
    "Baja la mirada y deja de tensarse tanto, parece menos cargada."
    mc "(En un tono más suave)"
    mc "Oye..."
    mc "Todavía tenemos que ir a la cita."
    mc "¿Te parece si vamos?"
    mc "Juntos."
    "Ella me mira más calmada."
    y "Sí, vamos."
    mc "Tomo su mano suavemente contra la mía."
    mc "Yuri, mirame."
    mc "Intentare que todo salga bien, lo prometo."
    mc "Allá vamos."
    # Se transporta el escenario a una sala de espera.
    mc "Vale, aquí es."
    "Miro al reloj colgando encima de la puerta."
    mc "Justo a tiempo."
    mc "El psiquiatra debería estar aquí en cualquier segund-"
    "Sin tiempo para terminar mi oración, un hombre sale de una habitación."
    "Es un hombre en la edad adulta, no es tan joven ni tan señor, con un cabello negro que empieza"
    "por un gris"
    "Él viste uno de esos trajes de moda, un traje típico de una revista de ropa"
    "Unos buenos zapatos elegantes, una corbata negra, incluso tiene un reloj de oro, parece real..."
    dr "Doctor Peter Lankton, psiquiatra."
    dr "Es un placer conocerlo."
    "Tenemos un apretón de manos."
    dr "Tu debes ser [player], ¿Correcto?"
    mc "Sí señor, y esta es Yuri."
    "Él aprieta la mano de Yuri"
    y "..."
    "Bueno, esto es incomodo..."
    dr "Ah, comprendo. Puede que estés nerviosa por qué soy doctor. Lo sé."
    dr "Pero quiero que sepas que no hay nada que temer."
    "Él señala con su brazo la oficina."
    dr "Entonces, ¿Quieres pasar e iniciamos la sesión?"
    mc "Está bien, vamos."
    dr "Oh, lo lamento joven, pero por hoy quisiera solo hablar con la chica."
    mc "¿Qué? ¿Enserio?"
    dr "Solo por ahora. En las próximas sesiones podrás pasar, pero para la primera es mejor"
    "que sea entre doctor y paciente."
    "Supongo que puedo entender eso..."
    "Okay, esperare aquí."
    dr "Gracias por entenderlo."
    "Él se dirige a Yuri, quien no ha dicho ni una sola palabra desde que llegamos."
    dr "¿Deberíamos pasar?"
    y "..."
    dr "..."
    mc "Doctor, le importaría si hablara con ella por un momento."
    dr "No. Tómense su tiempo. Estaré en mi oficina, que entre cuando este lista."
    "El entra a su oficina y cierra la puerta."
    mc "¿Que estas pensando ahora mismo?"
    y "N-no...no p-puedo hacerlo."
    mc "No digas eso."
    "Pongo mis manos en sus hombros."
    mc "Escuchame."
    mc "Eres fuerte, puedes pasar por esto."
    mc "Cuando entres estaré aquí, y cuando salgas también estaré aquí."
    mc "Se que puede dar miedo abrirse a un completo extraño."
    mc "Pero necesito que nos ayudes a ayudarte. "
    y"..."
    "Yuri me mira fijamente."
    y "Okay..."
    y "Lo haré lo mejor que pueda."
    mc "´Eso es todo lo que pido."
    "Le doy un abrazo, y ella entra a la oficina."
    # Cambio de escena dentro de la consulta, perspectiva de Yuri
    "Aún dudando, entro a la consulta despacio."
    "Miro al suelo."
    "aprieto ligeramente las manos."
    "Doy un pequeño paso dentro y luego otro."
    # Nota: En esta parte pensé que podrían los artistas hacer un sprite del Dr. Lankton, pero es solo una
    "idea, todo puede cambiar si no están de acuerdo conmigo, estas son solo ideas que forman parte de"
    "un guion descartable y estoy totalmente de bien si no están de acuerdo conmigo."
    "El Dr. Lankton ya está sentado."
    "Él levanta la mirada para observarme con calma."
    "El Dr. Lankton se levanta ligeramente, solo lo justo."
    dr "Puedes sentarte donde te sientas más cómoda."
    "Asiento sin hablar."
    "Me siento en la silla frente al doctor."
    mc "acomodo la ropa."
    "Me cuesta mantener contacto visual."
    "Él se vuelve a sentar."
    "Se acomoda en la silla."
    "Hay un silencio breve."
    dr "Antes de empezar... esto es un espacio privado."
    dr "No tienes que decir nada que no quieras."
    dr "Podemos ir a tu ritmo."
    "Él baja el tono al decir esto último"
    "Asiento muy levemente."
    "Bajo la mirada y mis dedos se aprietan un poco más."
    "Hay un silencio nuevamente."
    dr "dime joven, ¿Qué te hizo venir hoy?"
    # Hay dos botones con dos opciones, la primera es "No lo sé... últimamente me siento rara y la
    #"otra es "Me cuesta mucho hablar con la gente", aunque en cualquiera de las dos el doctor dirá lo"
    "mismo, son meramente un detalle."
    dr "Entiendo."
    "Hay una pausa."
    "El doctor junta las manos."
    dr "¿Esto te pasa desde hace mucho tiempo?"
    "Miro hacia un lado"
    "Empiezo a dudar de si debería estar aquí."
    "Respiro suavemente, tratando de calmarme."
    "Inconscientemente, me acomodo la manga"
    mc "quedo paralizada cuando siento que el doctor ha mirado unas marcas breves"
    "Un terror indescriptible inunda mi mente."
    "Él rapidamente me mira a los ojos nuevamente sin decir nada"
    dr "A veces, este tipo de pensamientos vienen de algo mas grande"
    dr "Y no siempre es fácil hablarlo de inmediato"
    # Vuelven a haber dos opciones, la primera es " No...solo es eso y la segunda es "Hay cosas que
    "no sé como explicar bien."
    # Si escogemos la primera opción, el Dr. Lankton dirá lo siguiente:
    dr "Está bien. Podemos empezar por ahí entonces."
    "Si escogemos la segunda opción, el Dr. Lankton dirá"
    dr "Gracias por decírmelo."
    dr "No tienes que cargar con esto sola aquí."
    "El doctor se reclina ligeramente."
    # En cualquier opción, la sesión terminara así:
    dr "Podemos tener más sesiones para hablar de esto si así lo deseas."
    "si quieres puede acompañarnos tu amigo a las siguientes sesiones."
    "Miro mis manos."
    "La sesión a finalizado..."
    # Cambio de escena, volvemos a la perspectiva del Jugador.
    mc "Bueno, supongo que me quedare aquí esperando."
    "Tomo asiento, y miro alrededor."
    "La sala de espera esta llena de posters motivacionales, imágenes y otras cosas estúpidas."
    "-Miro hacia otra pared"
    "Un certificado de psicólogo Dr. Peter Lankton, blah, blah, blah, Universidad de Stanford, blah,"
    "blah, blah..."
    "Se ve que este tipo sabe totalmente de esto."
    "Eso me deja más tranquilo."
    " Por primera vez en este mes puedo relajarme un poco."
    "Quizás Yuri pueda tener la ayuda que necesita"
    "Despues de unos minutos el dr. Lankton y Yuri salen de la oficina."
    "Empujando a un lado mis pensamientos, me paro de la silla para hablar con él."
    mc "¿Todo bien Doctor?"
    dr "Tu amiga parece estar lidiando con algunos problemas."
    "Lo miro de forma confusa."
    mc "Ya veo..."
    dr "Aún es pronto para saber todo lo que esta sintiendo."
    dr "Considero que deberíamos trabajar en eso para ayudarla mejor."
    dr "Creo que seria bueno hacer otra citación, para poder ayudarle un poco mejor al"
    "respecto."
    dr "Recuerden que hay terapias, y médicos profesionales como yo que están al servicio"
    "para ustedes."
    "Él me da una sonrisa."
    mc "Gracias Doctor."
    mc "Y que hay de lo que ella de... usted sabe..."
    dr "Lo siento, pero si te refieres a algo de la consulta, eso es información privada la cual"
    "no puedo revelar."
    "Confidencialidad entre Paciente y Doctor."
    "Hay un extraño cambio en mi voz cuando dirijo ese termino a él."
    dr "Por supuesto, si ella quiere revelarte esa información, es la elección de ella."
    mc "Gracias Doctor."
    dr "Un placer."
    "Le doy un último apretón de manos y salgo con Yuri del edificio."
    "El resto de caminar a casa es tranquilo."
    "Ninguno de nosotros elije decir una palabra."
    "Vuelvo a sentir esa sensación de culpa, quizás fue muy duro para ella que yo la haya llevado a un"
    "sitio así."
    "Incluso pese a que era con buena intención."
    # Llegan a la casa
    "Caminamos adentro de la casa y Yuri toma asiento en el sofa."
    "Me paro enfrente de ella. Antes de sentarme y hablar con ella."
    "Necesito disculparme."
    mc "Yuri, yo-"
    y "[player]..."
    "Ella cubre su cara con sus manos."
    y "F-fue extraño."
    y "No sabía muy bien que decir."
    y "Fue más difícil de lo que esperaba..."
    y "Creo que aun necesito tiempo para acostumbrarme..."
    "Pongo mi brazo alrededor de ella."
    mc "Yuri, yo debí saber que esta mal forzarte a hacer algo como eso."
    "Ella baja su cabeza y se acerca más a mi."
    "Sus ojos lavanda están llenos de lágrimas."
    y "[player]... tú no me obligaste."
    y "Tú tienes razón para ayudarme..."
    y "Y-yo... quiero volver."
    y "¿Puedes programar otra cita?"
    "Estoy desconcertado."
    mc "¿Enserio?"
    y "Yo sé que esto es lo mejor para mi... y tú estas de mi lado..."
    y "Yo creo que podemos superarlo."
    mc "Siempre estaré de tu lado Yuri."
    mc "Yo..."
    mc "Tenía miedo."
    mc "Miedo de hacerte pasar por mucho."
    mc "Y... miedo de que no estuvieras bien con esto y que solo quisieras hacerme sentir tranquilo."
    y "¿Puedes hacerme un favor, [player]?"
    mc "Por supuesto."
    y "No sé como podría explicarle todo al doctor."
    mc "-Bueno..."
    mc "Soy todo oídos si me necesitas."
    y "No sé cómo explicarlo..."
    "Yuri evita mirarme."
    y "A veces siento que mi cabeza... nunca se calla."
    mc "No tienes que decirme todo ahora."
    y "Pero quiero intentarlo."
    "Ella aprieta lentamente sus mangas."
    y "Cuando mis padres discutían"
    y "Cuando era más pequeña... los libros me ayudaban mucho a distraerme."
    y "Podía ignorar todo por un rato."
    "Yuri guarda silencio."
    y "Eventualmente mi madre se separo de mi padre y de mi, y mi padre tuvo que tener un trabajo"
    "extra para soporte."
    y "Con todo eso pasando yo solo continúe reprimiendo mis sentimientos y leyendo mis libros."
    "y'Así he estado toda mi toda mi vida."
    "y''Ella se detiene otra vez para respirar lentamente y reunir más sus pensamientos."
    y "Pero después dejaron de ser suficientes."
    "Yuri mantiene la mirada fija en el suelo"
    y "No sabía cómo sacar todo eso de mi cabeza."
    y "Ni siquiera sabía exactamente qué estaba sintiendo."
    "Ella aprieta sus mangas con más fuerza."
    y "Y un día... simplemente lo hice, comencé a usarlos."
    "Su voz se vuelve más baja."
    y "Me asusté mucho después."
    y "Pensé que nunca volvería a hacerlo."
    "Yuri guarda silencio unos segundos."
    y "Pero por un momento... mi cabeza se sintió más tranquila."
    y "Y terminé regresando a eso cada vez que me sentía sobrepasada."
    "mc'  Esto es mucho para digerir pero... solo quería decir..."
    mc "No te juzgo."
    y "¿Q-qué?"
    mc "No creo que merecieras pasar por todo eso."
    mc "tampoco creo que seas una mala persona por no haber sabido manejarlo."
    mc "A veces las personas simplemente... no saben cómo manejar lo que sienten."
    mc "Nunca podre entender lo que sucede en tu cabeza."
    mc "Pero estoy bien con eso."
    mc "Porque aún seguiré mi promesa de nunca dejarte."
    mc "Juntos podremos enfrentarlo."
    "Miro lentamente las vendas que cubren sus brazos."
    "Dudo unos segundos antes de hablar."
    mc "Yuri..."
    mc "¿Crees que podríamos guardar los cuchillos por un tiempo?"
    "Ella se tensa inmediatamente."
    y "..."
    mc "Solo quiero que estés un poco más segura."
    "Yuri baja la mirada."
    y "Esta bien, te dejare guardarlos (player)"
    "sonrio con orgullo"
    mc "Lo superaras Yuri"
    # pasan algunos días
    "Yuri sigue yendo a terapia"
    "Todavia hay momentos incomodos"
    "Pero empieza a mejorar poquito a poquito"
    "En realidad"
    mc "Hace tiempo que Yuri no sale a ningún lugar solo para relajarse"
    "Quizás mi idea suena algo cliché."
    "Pero honestamente... creo que a Yuri le gustaría." "Pronto comienzo a escribirle a Yuri"
    mc "Buenos días Yuri, dormiste bien?"
    y "Si, en realidad siempre despierto temprano. Y tu?"
    mc "Oh bueno yo igual"
    "Gran mentira yo siempre duermo hasta tarde"
    mc "Oye te gustaría ir a la playa alrato? Creo que nos vendría bien relajarnos"
    y "A la playa?..."
    "tarda unos segundos en responder probablemente pensándolo"
    y "Por supuesto (player), a que hora?"
    "Su respuesta llegó más rápido esta vez."
    "Por alguna razón... eso me hizo sonreír."
    mc "Muy bien, hora de ponerme guapo"
    "o almenos intentarlo"
    # cambio de escena a la puerta de la casa
    "Veamos...creo que tengo todo listo"
    "Tal vez debería llevarle algo a Yuri, espero encontrar algo en el camino"
    "Y barato, muy importante esa parte"
    # cambio de escena a casa de Yuri
    "Encontre unos chocolates, falle en la parte de ser algo barato pero seguro que le gustaran"
    "*ding dong*"
    "Que no me reciba su padre, que no me reciba su padre"
    "No es un buen momento para conocerlo"
    "La puerta se abre y sale Yuri con un vestido blanco con flores moradas"
    mc "Oh..."
    "Por un segundo me quedo mirándola demasiado tiempo."
    mc "Ese es el vestido que compraste antes... ¿verdad?"
    "Yuri aparta ligeramente la mirada."
    y "S-si..."
    y "Es ese."
    y "Tu... te ves bien hoy también"
    "Bueno me atrapo, ahora yo soy el rojo"
    mc "Gracias Yuri, salgamos un rato"
    "Comenzamos a caminar juntos por la calle."
    "Al principio ninguno dice demasiado."
    "Pero curiosamente... el silencio no se siente incómodo, almenos yo me siento en paz y Yuri...."
    "Parece estar feliz también"
    y "Hace buen clima hoy..."
    mc "Sí."
    mc "Aunque pensé que haría más calor."
    "Yuri deja escapar una pequeña risa."
    "Es una risa suave."
    "Pero aun así logra hacerme sonreír."
    # cambio de escena a la playa
    "Llegamos hace unos minutos y la vista es hermosa"
    "Espera ese es... No puede ser"
    "Un señor que vende helados!"
    mc "Hey Yuri, quieres un helado?"
    "Yuri permanece mirando el mar."
    "Parece completamente distraída observando las olas."
    y "No traje dinero (player), ve y te espero aquí"
    "Bueno mi momento ha llegado"
    mc "Esta bien Yuri, solo dime de que lo quieres"
    "Yuri desvia la mirada y juguetea con su vestido, susurra algo que se escucha como 'fresa"
    "Sonrio por la linda reacción y compro los helados, luego vuelvo con Yuri"
    y "Gracias (player)"
    "Comenzamos a caminar cerca del mar"
    "El sonido de las olas llena el silencio entre nosotros."
    "Yuri sostiene sus sandalias entre las manos mientras caminamos cerca de la orilla."
    y "No recuerdo la última vez que vine a un lugar así."
    mc "¿Demasiada gente?"
    y "Mm... también."
    y "Pero supongo que nunca encontraba una razón para hacerlo."
    "El viento mueve ligeramente su cabello."
    mc "¿Y ahora?"
    "Yuri me mira por un momento antes de apartar la vista."
    y "Ahora creo que quería intentarlo."
    mc "Yo tampoco solia venir tanto, supongo que evitaba salir de mi cueva asi que felicidades por lograr sacarme Yuri"
    "yuri deja escapar una risita"
    y "Yo también lo evitaba, recuerdas?"
    mc "Si, somos igualitos"
    "caminamos varios minutos mas hasta encontrar una banca y por supuesto que nos sentamos"
    "en esta parte de la playa parece estar mas vacia y el sol comienza a irse dándonos una linda vista"
    y "Eh (player)... Gracias por traerme aquí, necesitaba relajarme"
    mc "No tienes que agradecer Yuri, yo..."
    mc "Disfruto pasar tiempo contigo"
    "Ella desvía la vista al suelo con una sonrisa."
    "Por un momento ninguno dice nada."
    "El sonido de las olas llena el silencio entre nosotros."
    "Normalmente odiaría un silencio tan largo."
    "Pero con Yuri... no es incómodo."
    y "Me alegra haber venido."
    mc "A mí también."
    "Yuri juega distraídamente con la manga de su vestido."
    y "Siento que últimamente... todo ha sido menos pesado."
    "Ella sonríe levemente mientras mira el mar."
    y "Bueno no perfecto."
    y "Pero... mejor."
    "Escucharla decir eso me hace sentir extrañamente aliviado."
    mc "Has estado esforzándote mucho."
    y "Mm..."
    "Yuri guarda silencio unos segundos."
    y "Gracias por quedarte conmigo, [player]."
    "Mi pecho se siente extraño al escuchar eso."
    mc "No tienes que agradecerme tanto..."
    mc "Quiero estar aquí."
    "Las palabras salen antes de que pueda pensarlas demasiado."
    "Yuri lentamente me mira."
    "Por un segundo siento que mi corazón deja de funcionar."
    mc "Yo..."
    mc "Creo que nunca había querido pasar tanto tiempo con alguien."
    "Yuri baja lentamente la mirada."
    "Sus dedos aprietan ligeramente la tela de su vestido."
    y "Yo tampoco..."
    "El viento mueve suavemente su cabello."
    "Yuri duda unos segundos."
    "Después... lentamente acerca su mano a la mía."
    "Mi corazón empieza a latir muchísimo más rápido."
    mc "Últimamente..."
    mc "Siento que pienso demasiado en ti."
    "En cuanto las palabras salen de mi boca quiero esconderme debajo de la arena."
    "Yuri me mira sorprendida."
    mc "No, espera, eso sonó raro..."
    "Ella deja escapar una pequeña risa."
    "Y eso solo hace que me ponga todavía más nervioso."
    mc "Lo que intento decir es que..."
    mc "Me gusta pasar tiempo contigo."
    mc "Mucho."
    "Mi pecho late tan fuerte que estoy seguro de que Yuri puede escucharlo."
    "Ella aparta la mirada lentamente."
    y "[player]..."
    y "Creo que yo también me siento así."
    "Saber lo que acaba de decir Yuri me pone feliz y en lugar de ponerme mas nervioso me tranquiliza"
    "Decido acercarme un poco mas y Yuri hace lo mismo"
    "Al estar tan cerca... mi corazón late con fuerza pero poco a poco terminamos dándonos un lindo beso"
    "Por primera vez en mucho tiempo... mi mente se siente tranquila." "Yuri no parece estar tan diferente a mi, esta... feliz"
    "Y mientras el sol termina de ocultarse..."
    "Por primera vez en mucho tiempo... el futuro no me parece tan aterrador."
    # Cambio de escena a la habitación de me
    mc "Vaya... si que debí dormir temprano"
    "después de una molesta alarma me levanto y me preparo para empezar el dia"
    mc "Muy bien que tenemos para desayunar hoy?"
    "No parezco un loco hablando solo verdad?"
    "Despues de desayunar algunos huevos me pongo a pensar que hare hoy"
    mc "Todavía es temprano..."
    "Supongo que podría salir a correr un rato."
    "Hace siglos que no hago ejercicio."
    "De hecho estoy seguro de que Yuri puede levantarme como si fuera una rama"
    "Despues de varios minutos corriendo no dejo de pensar en Yuri y todo lo de ayer, me pone tan feliz... pero a la vez estoy confundido"
    "De verdad somos nov-"
    "SMACK"
    "Me caí"
    mc "Maldita piedra..."
    "Espero que nadie haya visto eso"
    "Levanto la vista y hay una anciana paseando a su perro"
    mc "Eh se me cayo una moneda"
    "Su perro parece juzgarme"
    "Esto es humillante"
    # Cambio de escena al sofá de me
    mc "Bueno no pensé que regresaría con una bolsa de verduras congeladas"
    "*ding dong*"
    "Esa es Yuri? Aun estoy nervioso de verla después de ayer no nos hicimos novios oficialmente"
    "Me levanto la puerta y es... Sayori?"
    s "Holaa (player) cuanto tiempo"
    s "Espera desde cuando te gustan las verduras"
    mc "Buenos días a ti también Sayo, y resulta que son buenas para el dolor de cabeza"
    s "¿Dolor de cabeza?"
    mc "No preguntes."
    s "Te caíste, ¿verdad?"
    mc "¿Qué?"
    s "Te caíste."
    mc "¿Cómo sabes eso?"
    s "Porque tienes una bolsa de verduras congeladas pegada en la cabeza."
    mc "..."
    s "Y porque eres tú."
    "Suspiro."
    mc "Sí, me caí."
    s "Jejeje."
    mc "No te rías."
    s "Lo intentaré."
    "Lo dice mientras sigue riéndose."
    s "Aunque debo admitir que me sorprende."
    mc "¿Qué cosa?"
    s "Que te vea sonriendo otra vez."
    "Parpadeo confundido."
    mc "¿Sonriendo?"
    s "Sí."
    s "Últimamente parecías muy preocupado."
    "Su sonrisa se vuelve un poco más suave."
    s "Me alegra verte mejor."
    "Por un momento no sé qué responder."
    mc "Gracias, Sayori."
    "Ella vuelve a sonreír con normalidad."
    s "¡Perfecto!"
    s "Ahora que ya confirmé que sigues vivo tengo otra pregunta."
    mc "Tengo miedo de preguntar."
    s "¿Qué pasó con Yuri?"
    mc "¿Qué?"
    s "Vamos, vamos."
    s "No nací ayer."
    s "Y además ustedes dos son pésimos ocultando cosas."
    mc "No estamos ocultando nada."
    s "Ajá."
    s "Claro."
    s "Y yo soy la presidenta de la Tierra."
    mc "Hola señora presidenta"
    "Sayo me golpea en el hombro, supongo que lo merecia"
    "Ambos pasamos a mi sofá"
    mc "Esta bien, Yuri había pasado por algunos problemas después de lo del club"
    mc "La estuve apoyando y esta mejorando poco a poco"
    s "Me alegra que este mejorando, pero que hay entre ustedes ehh?"
    "Oh no ahora me molestara con esto hasta que sepa que salimos"
    mc "Bueno es mi amiga y la quiero igual que a ustedes."
    "Ni de broma igual que ellas."
    "Sayori me mira fijamente."
    "Demasiado fijamente."
    mc "¿Qué?"
    s "Nada."
    mc "Sayori."
    s "Nadaaa."
    "Definitivamente es algo."
    s "Solo estaba pensando que eres muy mal mentiroso."
    mc "¿Qué?"
    s "Cuando mientes miras hacia otro lado."
    mc "Eso no es cierto."
    s "Lo acabas de hacer."
    "Maldita sea."
    s "Así que..."
    "Se acerca un poco más."
    s "¿Te gusta Yuri?"
    mc "¿Qué clase de pregunta es esa?"
    s "Una muy simple."
    mc "Sayori."
    s "¿Si?"
    mc "Estás sonriendo demasiado."
    s "Porque sé que tengo razón."
    "Me dejo caer contra el respaldo del sofá."
    mc "Eres imposible."
    s "Entonces sí."
    mc "No dije eso."
    s "Tampoco dijiste que no."
    "Sayori levanta los brazos victoriosa."
    s "¡Ajá!"
    mc "No hagas eso."
    s "¡AJÁ!"
    "Creo que empiezo a entender por qué sus padres salen tanto."
    "Sayori se ríe durante unos segundos."
    "Pero poco a poco su sonrisa se vuelve más suave."
    s "Me alegra."
    mc "¿Eh?"
    s "Después de todo lo que pasó."
    s "Me alegra que los dos tengan algo bueno."
    "Por primera vez desde que llegó, su tono suena completamente sincero."
    s "Solo cuídala, ¿sí?"
    s "Y cuídate tú también, te ves cansado."
    "Creo que tiene un poco de razón, estos días lo han sido"
    mc "Estare bien Sayo, que hay de ti?"
    "Sayori parece sospechar que no hable de mi, desde cuando es tan observadora?"
    s "Bueno, yo estuve ocupada con cosas de la escuela ya que no iba tan bien pero estoy mejorando mucho"
    s "Natsuki después de lo del club ha estado tomando clases de cocina y te sorprendería lo bien que lo hace"
    "Bueno eso suena muy Nat"
    s "Y Monika, no supe mucho de ella después de lo del club. Esta esforzándose por una beca en la universidad y vaya que lo esta logrando"
    "Monika nunca presumio sus calificaciones pero diablos ya eran muy altas en ese entonces"
    mc "Me alegra escuchar eso."
    s "¿Verdad?"
    s "Aunque extraño un poco el club."
    "Su sonrisa se vuelve un poco más pequeña."
    "Yo también."
    "Por más problemas que hubiera tenido, seguía siendo un lugar al que podía ir después de clases."
    mc "Sí"
    "Durante unos segundos ninguno dice nada."
    s "Oye."
    mc "¿Hm?"
    s "¿Crees que algún día podamos volver a reunirnos?"
    mc "¿El club?"
    s "Aunque no sea oficialmente."
    "Me quedo pensándolo."
    "Supongo que no sería imposible."
    "Yuri ya está mejorando."
    "Natsuki parece estar ocupada pero sigue cerca."
    "Y Sayori claramente echa de menos esos días."
    mc "Tal vez."
    s "¡Eso significa que sí!"
    mc "Eso no fue lo que dije."
    s "¡Lo fue para mí!"
    "Sayori vuelve a reírse."
    "Es extraño."
    "Por primera vez en semanas la conversación no gira alrededor de problemas."
    "Solo estamos hablando."
    "Como antes."
    s "Bueno."
    "Ella se pone de pie."
    s "Creo que ya molesté suficiente por hoy."
    mc "Eso significa que alguna vez dejas de molestar."
    s "¡Oye!"
    "Me golpea suavemente el brazo."
    "Otra vez."
    s "Ah, cierto."
    "Se detiene justo antes de llegar a la puerta."
    s "Si ves a Yuri..."
    mc "¿Si?"
    s "Dile que la extraño."
    "Su tono vuelve a sonar sincero."
    s "Y que me alegra que esté mejor."
    "Antes de que pueda responder, Sayori ya está saliendo por la puerta."
    "Qué mujer tan peligrosa."
    "Mi teléfono vibra."
    "Un nuevo mensaje."
    y "Buenos dias, [player]."
    y "¿Cómo estás?"
    mc "Hola Yuri, me duele un poco la cabeza, y tu?"
    y "Estas bien? Yo estoy bien, me siento liberada ahora estoy cocinando"
    mc "Estoy bien, yo... también me siento feliz, quieres salir al rato?"
    "Yuri parece contestar mas rápido esta vez"
    y "Si, a que hora planeas venir?"
    "Nos ponemos de acuerdo"
    "Muy bien, tal vez sea nuestra oportunidad de aclarar las cosas entre nosotros"
    "Estoy nervioso"
    "Guardo el teléfono en mi bolsillo."
    "Supongo que ya no hay vuelta atrás."
    "Intento distraerme ordenando un poco la casa antes de salir."
    "Lo cual dura un rato hasta que termino."
    mc "Esto es inútil."
    "Entre más intento pensar en otra cosa, más termino pensando en Yuri."
    "¿Se supone que estar enamorado funciona así?"
    "Decido salir antes de volverme loco."
    # Cambio de escena a la calle
    "El aire de la tarde es agradable."
    "Camino tranquilamente mientras reviso la hora en mi teléfono."
    "Aun es un poco temprano."
    "Probablemente porque llevo media hora preparándome para una salida que ni siquiera es una cita oficial."
    n "¡Oye!"
    "Me detengo."
    "Conozco esa voz."
    "Y también conozco ese tonito."
    n "¡Tú!"
    mc "Hola, Natsuki."
    n "¿Hola, Natsuki?"
    n "¿Eso es todo?"
    n "Hace semanas que no te veo."
    mc "Tú tampoco me has buscado."
    n "Porque tengo cosas importantes que hacer."
    mc "¿Como qué?"
    n "Postres."
    mc "Entendible."
    "Por alguna razón parece satisfecha con esa respuesta."
    n "Entonces..."
    "Me señala con el dedo."
    n "¿Vas a ver a Yuri?"
    mc "¿Qué?"
    n "Era muy obvio."
    mc "¿Desde cuándo todo el mundo lo sabe?"
    n "No respondas una pregunta con otra pregunta."
    "Suspiro."
    mc "Sí."
    n "Ajá."
    "Su sonrisa se vuelve sospechosamente grande."
    mc "No hagas esa cara."
    n "¿Qué cara?"
    mc "Esa cara."
    n "La cara de que tengo razón."
    mc "Exactamente esa."
    mc "No tiene sentido ocultarlo, Sayori ya me atormento con eso hace rato."
    n "Que?"
    mc "Larga historia"
    n "Entonces cuando lo van a hacer oficial?"
    mc "Bueno honestamente no tengo idea, ayer fue un dia especial para ambos pero no le dije"
    "Natsuki suspira con una sonrisa"
    n "Esa Yuri, no debería decirtelo porque se supone que es tu novia pero estoy seguro de que estará lista"
    n "Mas te vale que la cuides o hare ese moretón de tu cabeza mas grande"
    "Espera enserio se nota?"
    mc "No me atrevería a desafiarte"
    n "Como sea tengo que irme pero dale esto, dile que es de tu parte"
    "Natsuki me entrega una galleta en forma de gato"
    n "No creas que es porque quiero ayudarte tonto, quiero que ella sea feliz"
    "Clasica tsundere"
    mc "Gracias Nat, te debo una"
    n "Como sea tonto"
    "Natsuki desvía la mirada."
    "Juraría que estaba sonriendo."
    "Pronto se despide"
    "Guardo cuidadosamente la galleta."
    "Ahora tengo una misión."
    "No aplastarla antes de llegar."
    # Cambio de escena a casa de yuri
    "Tras caminar varios minutos finalmente llego a la casa de Yuri."
    "Respiro profundo."
    "Por alguna razón estoy más nervioso ahora que en la playa."
    "*Ding dong.*"
    "Escucho pasos acercándose."
    "La puerta se abre."
    "Yuri aparece frente a mí."
    "Y por un segundo olvido completamente lo que iba a decir."
    y "[player]?"
    mc "Hola Yuri."
    y "Hola."
    "Nos quedamos viendo durante unos segundos."
    "Esto es ridículo."
    "Nos besamos ayer."
    "¿Por qué estamos actuando como si fuera la primera vez que hablamos?"
    mc "Antes de que diga cualquier cosa..."
    "Levanto la pequeña bolsa."
    mc "Tengo algo para ti."
    y "¿Eh?"
    mc "Bueno..."
    mc "Técnicamente es de Natsuki."
    "Lo siento Nat pero no me llevare tu crédito"
    y "¿Natsuki?"
    "Los ojos de Yuri se abren un poco."
    mc "Me la encontré por el camino."
    mc "Y me obligó a entregarte esto."
    y "..."
    "Yuri observa la galleta en forma de gato."
    "Por un momento parece completamente sorprendida."
    y "Ella sigue haciendo estas cosas..."
    "Su voz se vuelve más suave."
    y "Nunca cambia."
    "Me invita a pasar y entro"
    mc "Entonces no han hablado demasiado?"
    y "No en realidad, casi nada después de que dejamos el club"
    y "Nos peleábamos mucho pero se que era una buena amiga, especialmente por las cosas como estas"
    mc "Si, suena como a nuestra tsun local"
    mc "Yo también había hablado poco con Sayo hasta hoy, vino a emboscarme hace rato."
    y "¿Sayori fue a tu casa?"
    mc "Sí."
    mc "Y estuvo molestándome durante media hora."
    y "Eso suena como Sayori."
    "Yuri sonríe un poco."
    mc "También preguntó mucho por ti."
    y "¿Por mi?"
    mc "Claro."
    mc "Le alegró saber que estás mejor."
    "Yuri baja la vista hacia la galleta."
    y "Ya veo..."
    "Su voz suena extrañamente baja."
    mc "¿Pasa algo?"
    y "No es nada."
    "Parece pensarlo unos segundos."
    y "Supongo que me alegra."
    y "Solo que..."
    y "Mientras yo pude estar ahi"
    y "Ella lo estuvo."
    mc "Yuri..."
    y "No me malinterpretes."
    y "No estoy molesta."
    "Por un momento parece avergonzada de haber dicho eso."
    mc "Bueno."
    mc "Si te sirve de consuelo, Sayori me pego almenos dos veces."
    "Yuri deja escapar una pequeña risa."
    y "Es por eso que tienes ese moretón en la cabeza?."
    "UHH enserio? Exterminare las rocas"
    mc "Además..."
    mc "Ella estaba preocupada por ti."
    mc "Natsuki también."
    "Yuri observa nuevamente la galleta de gato."
    y "Quizás debería hablar con ellas."
    mc "Creo que les gustaría mucho eso."
    mc "Tambien me hablo sobre reunirnos de nuevo, dudo que rechacen algo así"
    "Un silencio aparece de la nada, después recuerdo a lo que vine"
    "No tiene sentido posponerlo, aquí vamos"
    mc "Yuri... sobre ayer, nosotros estamos... ya sabes"
    mc "Estamos saliendo?"
    "La pregunta parece sorprender a Yuri, no la culpo"
    y "Solo si tu quieres..."
    "Dice sonrojada"
    mc "Estas bromeando? Por supuesto"
    "Me levanto emocionado a abrazarla"
    "Ella me devuelve el abrazo."
    "Un poco torpemente."
    "Como si todavía no estuviera acostumbrada a algo así."
    "Por un momento ninguno de los dos dice nada."
    "Simplemente nos quedamos ahí."
    "Es extraño."
    "Hace unos meses probablemente habría pensado que algo así nunca podría pasar."
    y "[player]..."
    mc "¿Sí?"
    y "Todavía se siente un poco irreal."
    mc "¿Qué cosa?"
    y "...Todo esto."
    "Yuri desvía la mirada."
    y "Tú."
    y "Nosotros."
    "Una pequeña sonrisa aparece en mi rostro."
    mc "Créeme."
    mc "Yo tampoco esperaba terminar aquí."
    y "Ujuju..."
    "Yuri deja escapar una pequeña risa."
    "Creo que es la primera vez que la escucho reír tan tranquila."
    "Después de unos segundos finalmente nos separamos."
    mc "Bueno."
    mc "Ahora tengo una novia oficialmente."
    y "P-por favor no lo digas así..."
    "Su rostro se vuelve completamente rojo."
    mc "¿Por qué no?"
    y "Porque es vergonzoso..."
    mc "A mí me parece genial."
    "Yuri intenta ocultar su sonrisa."
    "Fracasa miserablemente."
    "Me dejo caer nuevamente en el sofá junto a ella."
    "Por un momento el silencio vuelve."
    "Pero esta vez ninguno parece incómodo."
    "Entonces recuerdo algo."
    mc "Oh, entonces crees que deberíamos reunirnos de nuevo?"
    y "Hm?"
    "Yuri parpadea sorprendida."
    y "¿Reunirnos?"
    mc "Sí."
    mc "Tú, yo, Sayori y Natsuki."
    "Yuri guarda silencio unos segundos."
    y "Eso... suena agradable."
    mc "Yo pensé lo mismo."
    "Por primera vez en un tiempo, la idea de volver a reunirnos parece esperanzadora."
    mc "Que tal si las llamamos ahora? Aun no es tan tarde"
    y "Ahora?... Esta bien hagámoslo"
    "Tomo mi celular y le marco a nuestra tsundere favorita"
    "Responde en unos segundos"
    n "Ahora que (player)?"
    mc "Buenas noches a ti también Nat"
    mc "Oye, te gustaría reunirnos de nuevo? Ya sabes, tu, yo, Sayo, Yuri"
    n "Bueno tengo un tiempo sin verlas, ire"
    "poco tiempo después nos ponemos de acuerdo acerca de cuando y donde, Yuri y ella se despiden"
    mc "Diría que te toca convencer a Sayori."
    y "¿Convencerla?"
    mc "Tienes razón."
    mc "Ni siquiera va a dejarme terminar la frase."
    "Yuri rie por eso"
    mc "Hola sayo, recuerdas lo que dijiste hace rato sobre reunirnos? Yuri y Nat están de acuerdo"
    s "EN SERIOOOOO?"
    s "Ire"
    mc "Espera aun ni siquiera sabes cuando"
    s "Cuando?"
    mc "El viernes, mi casa"
    s "No necesito saber mas, chao (player)"
    "Sayori cuelga"
    mc "Que dificil fue convencer a Sayori"
    y "Asi es ella"
    mc "Yo también tengo que regresar a casa Yuri"
    "Yuri me acompaña a su puerta"
    mc "Nos vemos Yuri"
    y "Adios (player)"
    "Ella me abraza y se lo devuelvo"
    "Despues regreso a casa"
    # Cambio de escena a habitación de me
    "*PIP PIP*"
    mc "Maldita alarma"
    "Me preparo para iniciar el dia"
    "Veo de reojo mi consola de videojuegos"
    mc "Algun dia volveré a tener tiempo para ti amigo"
    "Bajo a la cocina a desayunar algunas tostadas y café negro"
    mc "Muy bien, creo que tengo tiempo para correr de nuevo"
    "Cuando apenas me iba a preparar para salir escucho mi timbre"
    mc "Si es Sayori me sorprenderá que este despierta ahora"
    "Camino y abro la puerta"
    s "Holaa (Player)"
    mc "Honestamente esta vez dude que fueras tu, es muy temprano"
    s "Queria ayudar a mi mama a limpiar mi casa hoy, y nos sobro tiempo."
    mc "Wow quien eres y que le hiciste a mi Sayori."
    "Sayori entra a la casa sin esperar invitación."
    mc "¿Sabes? Normalmente la gente espera a que la inviten."
    s "Demasiado tarde."
    "Se deja caer en el sofá como si viviera aquí."
    mc "Buenos días para ti también."
    s "Buenos días."
    "Por un momento parece buscar algo que decir."
    s "Estoy emocionada por la reunión."
    mc "Se notó por el grito de ayer."
    s "¡Era un grito completamente normal!"
    mc "Creo que vi volar algunos pajaros cuando sono."
    "Sayori me saca la lengua."
    s "Oye..."
    "Su tono cambia un poco."
    s "¿Puedo preguntarte algo?"
    mc "Eso depende de qué tan peligroso sea."
    s "¿Y si invitamos a Monika?"
    ""
    "Ah."
    "Sabía que algo raro estaba pasando."
    mc "No."
    s "Ni siquiera lo pensaste."
    mc "No."
    s "(Player)..."
    mc "Sayori."
    "Ella suspira."
    s "Sé que estás enojado."
    mc "No estoy enojado."
    "Pausa."
    mc "Bueno, sí."
    s "Lo sabía."
    mc "Lo que hizo estuvo terrible."
    mc "Y Yuri fue quien terminó pagandolo."
    s "Lo sé."
    "Su respuesta llega tan rápido que me sorprende."
    s "No estoy diciendo que lo que hizo estuvo bien."
    s "Solo digo que..."
    s "Monika tampoco ha estado bien desde entonces."
    "Frunzo el ceño."
    mc "¿A qué te refieres?"
    s "Ha estado concentrándose en la escuela y esta yendo a terapias."
    s "Apenas y puede seguir."
    s "Esta demasiado estresada."
    s "Creo que necesita tranquilizarse un poco."
    "Eso no cambia lo que pasó."
    s "No tienes que perdonarla hoy."
    s "Ni mañana."
    s "Solo... piénsalo."
    "Sayori se pone de pie."
    s "Bueno."
    s "Ya cumplí mi misión."
    mc "¿Misión?"
    s "Sí."
    s "Ahora me iré antes de que me rechaces otra vez."
    mc "No prometi nada."
    s "Lo sé."
    "Ella sonríe."
    s "Nos vemos el viernes."
    "Y después se marcha."
    "Cierro la puerta."
    "En un instante la casa vuelve a quedar en silencio."
    "Monika."
    "No estaba seguro de querer pensar en ella."
    "Pero ahora no puedo quitármela de la cabeza."
    "Si esta yendo a terapia significa que se arrepiente, no?"
    "Aun asi eso no cambia lo que hizo"
    "Deberia preguntarle a Yuri"
    "Saco mi teléfono y le marco"
    mc "Buenos días Yuri, como estas?"
    y "Buenos días (player), me siento muy bien, y tu?"
    "Eso me hace sonreir"
    mc "Tambien estoy bien Yuri, oye Sayori vino a invadirme de nuevo y me dijo algo"
    mc "Queria que invitaramos a Monika, me conto que la a pasado mal y esta yendo a terapia"
    mc "Supongo que se arrepiente pero aun estoy molesto con ella y eso no cambia las cosas"
    mc "Tu que piensas"
    y "Creo que si ella tiene intención debemos darle una segunda oportunidad"
    y "Despues de todo yo se exactamente lo que se siente perder el control"
    mc "..."
    "Yo honestamente aun desconfio de esto pero se que Yuri esta haciendo lo correcto"
    "Ademas también soy un cursi que cree en las segundas oportunidades"
    mc "Si le tienes fe, entonces no perderíamos nada intentándolo"
    y "¿Estás seguro?"
    mc "No."
    mc "Para nada."
    mc "Pero tampoco quiero quedarme preguntándome qué habría pasado si la invitabamos."
    y "..."
    y "Gracias."
    mc "No me agradezcas todavía."
    mc "Si intenta algo raro, Natsuki la lanzará por una ventana."
    y "¡[player]!"
    mc "Estoy bromeando."
    y "..."
    mc "Más o menos."
    mc "Esta bien Yuri, nos vemos luego"
    y "Adios (player) cuidate"
    "Cuelgo la llamada"
    "Miro la lista de contactos."
    "Mi dedo se detiene sobre un nombre."
    "Hace unos dias jamás habría pensado en llamarla."
    "Y honestamente..."
    "Todavía no estoy seguro de querer hacerlo."
    "Ring..."
    "Ring..."
    "Ring..."